import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

/**
 * GENERATED by scripts/gen-package-runtime-loaders.mjs - do not edit directly.
 * This file is shipped with the package extension and intentionally avoids
 * static SDK imports so project-local installed extensions can load it.
 */

const PM_PACKAGE_ROOT_ENV = "PM_CLI_PACKAGE_ROOT";
const CURRENT_EXTENSION_ROOT = path.dirname(fileURLToPath(import.meta.url));
const EXTENSION_NAME = "todos";
const PACKAGE_NAME = "pm-todos";
const DIAGNOSTIC_NAME = "todos";

export type PackageRuntimeModule = Record<string, unknown>;

function resolvePackageRootCandidates(): string[] {
  const candidates: string[] = [];
  const envRoot = process.env[PM_PACKAGE_ROOT_ENV];
  if (typeof envRoot === "string" && envRoot.trim().length > 0) {
    candidates.push(path.resolve(envRoot.trim()));
  }
  const argvEntry = typeof process.argv[1] === "string" ? process.argv[1].trim() : "";
  if (argvEntry.length > 0) {
    const resolvedEntry = path.resolve(argvEntry);
    const entryDir = path.dirname(resolvedEntry);
    candidates.push(path.resolve(entryDir, ".."));
    candidates.push(path.resolve(entryDir, "../.."));
    candidates.push(path.resolve(entryDir, "../../.."));
  }
  return [...new Set(candidates)];
}

export async function loadPackageRuntimeModule(): Promise<PackageRuntimeModule> {
  const attempted: string[] = [];
  for (const packageRoot of resolvePackageRootCandidates()) {
    const modulePaths = [
      path.join(packageRoot, ".agents", "pm", "extensions", EXTENSION_NAME, "runtime.js"),
      path.join(packageRoot, "packages", PACKAGE_NAME, "extensions", EXTENSION_NAME, "runtime.js"),
    ];
    for (const modulePath of modulePaths) {
      attempted.push(modulePath);
      try {
        return await import(pathToFileURL(modulePath).href) as PackageRuntimeModule;
      } catch {
        // Try the next package-root candidate.
      }
    }
  }

  const localRuntimePath = path.join(CURRENT_EXTENSION_ROOT, "runtime.js");
  attempted.push(localRuntimePath);
  try {
    return await import(pathToFileURL(localRuntimePath).href) as PackageRuntimeModule;
  } catch {
    // Fall through to the diagnostic below.
  }

  throw new Error(
    `Unable to resolve packaged ${DIAGNOSTIC_NAME} extension runtime module. ` +
      `Tried: ${attempted.join(", ")}. Ensure the installed extension includes runtime.js or PM_CLI_PACKAGE_ROOT points to an installed pm package root.`,
  );
}
