/**
 * @module sdk/completion/bash
 * Renders Bash completion from shared command contracts and runtime schema.
 */
import {
  PM_NAMESPACED_COMMAND_ALIASES
} from "../cli-contracts.js";
import type { CompletionRuntimeConfig } from "./shared.js";
import { AGGREGATE_FLAGS,ALL_COMMANDS,APPEND_FLAGS,CALENDAR_FLAGS,CLAIM_MUTATION_FLAGS,CLOSE_MANY_FLAGS,CLOSE_MUTATION_FLAGS,CLOSE_TASK_MUTATION_FLAGS,COMPLETION_SHELL_CHOICES,CONTEXT_FLAGS,CONTRACTS_FLAGS,COPY_FLAGS,CREATE_FLAGS,DELETE_MUTATION_FLAGS,DEPS_FLAGS,DUPLICATES_FLAGS,EVENTS_FLAGS,EXTENSION_LIFECYCLE_ACTIONS,EXTENSION_LIFECYCLE_FLAGS,FOCUS_FLAGS,GET_FLAGS,GLOBAL_COMPLETION_INLINE_PATTERNS,GLOBAL_COMPLETION_SWITCH_PATTERNS,GLOBAL_COMPLETION_VALUE_PATTERNS,GLOBAL_FLAGS,GRAPH_FLAGS,GUIDE_FLAGS,GUIDE_TOPIC_CHOICES,HEALTH_FLAGS,HISTORY_AUTHOR_ACKNOWLEDGE_FLAGS,HISTORY_FLAGS,HISTORY_LEAVES,HISTORY_OPERATION_FLAGS,INIT_FLAGS,LIST_FLAGS,MEET_FLAGS,MUTATION_FLAGS,NAMESPACE_NOUNS,NAMESPACE_PREFIXES,NEXT_FLAGS,PACKAGE_LIFECYCLE_ACTIONS,PACKAGE_LIFECYCLE_FLAGS,PLAN_FLAGS,PLAN_SUBCOMMANDS_LIST,RELEASE_MUTATION_FLAGS,REMIND_FLAGS,SCHEMA_SUBCOMMAND_CHOICES,SEARCH_FLAGS,STATS_FLAGS,UPDATE_FLAGS,UPDATE_MANY_FLAGS,UPGRADE_FLAGS,completionNamespaceLeaves,completionStatusValues,completionTypeValues,joinCompletionValues,mergeFlagStrings,shellDoubleQuote } from "./shared.js";

/** Emit a TTL-cached Bash status or type resolver with a source-escaped fallback when the helper returns no choices. */
function renderBashDynamicChoiceResolver(
  kind: "status" | "type",
  command: "completion-statuses" | "completion-types",
  fallback: string,
): string[] {
  const envKind = kind.toUpperCase();
  const cacheVar = `PM_COMPLETION_${envKind}_CACHE`;
  const cacheTsVar = `PM_COMPLETION_${envKind}_CACHE_TS`;
  const ttlVar = `PM_COMPLETION_${envKind}_TTL`;
  const escapedFallback = shellDoubleQuote(fallback);
  return [
    `_pm_completion_${kind}_choices() {`,
    "  local now ttl cache_ts resolved",
    '  now="$(date +%s 2>/dev/null || echo 0)"',
    `  ttl="\${${ttlVar}:-120}"`,
    `  cache_ts="\${${cacheTsVar}:-0}"`,
    `  if [[ -n "\${${cacheVar}:-}" && "$now" -ne 0 && $((now - cache_ts)) -lt "$ttl" ]]; then`,
    `    printf '%s\\n' "$${cacheVar}"`,
    "    return 0",
    "  fi",
    `  resolved="$(pm ${command} 2>/dev/null)"`,
    '  if [[ -z "$resolved" ]]; then',
    `    resolved="${escapedFallback}"`,
    "  fi",
    `  ${cacheVar}="$resolved"`,
    `  ${cacheTsVar}="$now"`,
    `  printf '%s\\n' "$${cacheVar}"`,
    "}",
  ];
}

/** Implements generate bash script for the public runtime surface of this module. */
export function generateBashScript(
  itemTypes: string[] = [],
  tags: string[] = [],
  eagerTagExpansion = false,
  runtime: CompletionRuntimeConfig = {},
): string {
  const namespaceLeaves = completionNamespaceLeaves(runtime);
  const cmds = ALL_COMMANDS.join(" ");
  const useDynamicTypeExpansion = itemTypes.length === 0;
  const typeValues = completionTypeValues(itemTypes, runtime);
  const statusValues = completionStatusValues(runtime);
  const tagValues = joinCompletionValues(tags);
  const listFlags = mergeFlagStrings(LIST_FLAGS, runtime.command_flags?.list);
  const createFlags = mergeFlagStrings(
    CREATE_FLAGS,
    runtime.command_flags?.create,
  );
  const updateFlags = mergeFlagStrings(
    UPDATE_FLAGS,
    runtime.command_flags?.update,
  );
  const updateManyFlags = mergeFlagStrings(
    UPDATE_MANY_FLAGS,
    runtime.command_flags?.["update-many"],
  );
  const searchFlags = mergeFlagStrings(
    SEARCH_FLAGS,
    runtime.command_flags?.search,
  );
  const calendarFlags = mergeFlagStrings(
    CALENDAR_FLAGS,
    runtime.command_flags?.calendar,
  );
  const contextFlags = mergeFlagStrings(
    CONTEXT_FLAGS,
    runtime.command_flags?.context,
  );
  const useEagerTagExpansion = eagerTagExpansion || tags.length > 0;
  // Note: "${...}" inside regular (non-template) strings are literal characters,
  // not JS interpolation. Only backtick template literals interpolate ${...}.
  const compgen = (flags: string): string =>
    `$(compgen -W "${shellDoubleQuote(flags.replace(/([^a-zA-Z0-9_:./\s-])/g, "\\$1"))}" -- "$cur")`;
  return [
    "# bash completion for pm",
    "# Source this file or add 'eval \"$(pm completion bash)\"' to ~/.bashrc",
    "",
    ...(useDynamicTypeExpansion
      ? [
          ...renderBashDynamicChoiceResolver(
            "type",
            "completion-types",
            typeValues,
          ),
          "",
        ]
      : []),
    ...renderBashDynamicChoiceResolver(
      "status",
      "completion-statuses",
      statusValues,
    ),
    "",
    "# Quote each word before compgen performs its own shell expansion.",
    "_pm_completion_wordlist() {",
    "  local line",
    "  local -a values",
    "  while IFS= read -r line; do",
    "    read -r -a values <<< \"$line\"",
    "    printf '%q ' \"${values[@]}\"",
    "  done <<< \"$1\"",
    "}",
    "",
    "_pm_completion() {",
    "  local cur prev words cword",
    "  _init_completion 2>/dev/null || {",
    '    cur="${COMP_WORDS[COMP_CWORD]}"',
    '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
    "    cword=$COMP_CWORD",
    "  }",
    "",
    "  if [[ $cword -eq 1 ]]; then",
    `    COMPREPLY=(${compgen(cmds)})`,
    "    return 0",
    "  fi",
    "",
    '  if [[ "$prev" == "--type" ]]; then',
    useDynamicTypeExpansion
      ? '    COMPREPLY=($(compgen -W "$(_pm_completion_wordlist "$(_pm_completion_type_choices)")" -- "$cur"))'
      : `    COMPREPLY=(${compgen(typeValues)})`,
    "    return 0",
    "  fi",
    "",
    '  if [[ "$prev" == "--status" ]]; then',
    '    COMPREPLY=($(compgen -W "$(_pm_completion_wordlist "$(_pm_completion_status_choices)")" -- "$cur"))',
    "    return 0",
    "  fi",
    "",
    ...(useEagerTagExpansion
      ? [
          '  if [[ ( "$prev" == "--tag" || "$prev" == "--tags" ) && ! ( ( "${COMP_WORDS[1]}" == "package" || "${COMP_WORDS[1]}" == "packages" ) && "${COMP_WORDS[2]}" == "upgrade" ) ]]; then',
          `    COMPREPLY=(${compgen(tagValues)})`,
          "    return 0",
          "  fi",
        ]
      : [
          '  if [[ ( "$prev" == "--tag" || "$prev" == "--tags" ) && ! ( ( "${COMP_WORDS[1]}" == "package" || "${COMP_WORDS[1]}" == "packages" ) && "${COMP_WORDS[2]}" == "upgrade" ) ]]; then',
          "    local now ttl cache_ts tag_values",
          '    now="$(date +%s 2>/dev/null || echo 0)"',
          '    ttl="${PM_COMPLETION_TAG_TTL:-120}"',
          '    cache_ts="${PM_COMPLETION_TAG_CACHE_TS:-0}"',
          '    tag_values="${PM_COMPLETION_TAG_CACHE:-}"',
          '    if [[ -z "$tag_values" || "$now" -eq 0 || $((now - cache_ts)) -ge "$ttl" ]]; then',
          '      tag_values="$(pm completion-tags 2>/dev/null)"',
          '      PM_COMPLETION_TAG_CACHE="$tag_values"',
          '      PM_COMPLETION_TAG_CACHE_TS="$now"',
          "    fi",
          '    COMPREPLY=($(compgen -W "$(_pm_completion_wordlist "$tag_values")" -- "$cur"))',
          "    return 0",
          "  fi",
        ]),
    "",
    '  if [[ "$prev" == "--tag" && ( ( "${COMP_WORDS[1]}" == "package" || "${COMP_WORDS[1]}" == "packages" ) && "${COMP_WORDS[2]}" == "upgrade" ) ]]; then',
    "    COMPREPLY=()",
    "    return 0",
    "  fi",
    "",
    '  local cmd="" command_path="" word_index=1 word',
    "  while (( word_index < cword )); do",
    '    word="${COMP_WORDS[word_index]}"',
    '    case "${word//_/-}" in',
    `      ${GLOBAL_COMPLETION_VALUE_PATTERNS}) (( word_index += 2 )); continue ;;`,
    `      ${GLOBAL_COMPLETION_INLINE_PATTERNS}|${GLOBAL_COMPLETION_SWITCH_PATTERNS}) (( word_index++ )); continue ;;`,
    "      --) break ;;",
    "    esac",
    '    if [[ -z "$cmd" ]]; then',
    '      cmd="$word"',
    '      [[ "$cmd" == "ctx" ]] && cmd="context"',
    '      command_path="$cmd"',
    `      case "$cmd" in ${NAMESPACE_NOUNS.join("|")}) ;; *) break ;; esac`,
    "    else",
    '      case "$command_path $word" in',
    ...PM_NAMESPACED_COMMAND_ALIASES.map((entry) => `        "${entry.canonical}") cmd="${entry.alias}"; command_path="${entry.canonical}" ;;`),
    '        *) break ;;',
    "      esac",
    `      case "$command_path" in ${NAMESPACE_PREFIXES.map((prefix) => `"${prefix}"`).join("|")}) ;; *) (( word_index++ )); break ;; esac`,
    "    fi",
    "    (( word_index++ ))",
    "  done",
    '  case "$cmd" in',
    ...HISTORY_OPERATION_FLAGS.flatMap((entry) => [
      `    ${entry.alias})`,
      `      COMPREPLY=(${compgen(entry.flags)})`,
      "      return 0",
      "      ;;",
    ]),
    "    list)",
    `      COMPREPLY=(${compgen(listFlags)})`,
    "      ;;",
    "    aggregate)",
    `      COMPREPLY=(${compgen(AGGREGATE_FLAGS)})`,
    "      ;;",
    "    duplicates)",
    `      COMPREPLY=(${compgen(DUPLICATES_FLAGS)})`,
    "      ;;",
    "    create)",
    `      COMPREPLY=(${compgen(createFlags)})`,
    "      ;;",
    "    copy)",
    `      COMPREPLY=(${compgen(COPY_FLAGS)})`,
    "      ;;",
    "    focus)",
    `      COMPREPLY=(${compgen(FOCUS_FLAGS)})`,
    "      ;;",
    "    update)",
    `      COMPREPLY=(${compgen(updateFlags)})`,
    '      if [[ $word_index -eq $cword ]]; then',
    `        COMPREPLY+=(${compgen(namespaceLeaves.update)})`,
    "      fi",
    "      ;;",
    "    update-many)",
    `      COMPREPLY=(${compgen(updateManyFlags)})`,
    "      ;;",
    "    calendar|cal)",
    `      COMPREPLY=(${compgen(calendarFlags)})`,
    "      ;;",
    "    context|ctx)",
    `      COMPREPLY=(${compgen(contextFlags)})`,
    '      if [[ $word_index -eq $cword ]]; then',
    `        COMPREPLY+=(${compgen(namespaceLeaves.context)})`,
    "      fi",
    "      ;;",
    "    ops)",
    `      COMPREPLY=(${compgen(`${GLOBAL_FLAGS} ${namespaceLeaves.ops}`)})`,
    "      ;;",
    "    next)",
    `      COMPREPLY=(${compgen(NEXT_FLAGS)})`,
    "      ;;",
    "    guide)",
    `      COMPREPLY=(${compgen(`${GUIDE_FLAGS} ${GUIDE_TOPIC_CHOICES}`)})`,
    "      ;;",
    "    search)",
    `      COMPREPLY=(${compgen(searchFlags)})`,
    "      ;;",
    "    reindex)",
    `      COMPREPLY=(${compgen("--mode --progress --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    init)",
    `      COMPREPLY=(${compgen(`${INIT_FLAGS} --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help`)})`,
    "      ;;",
    "    config)",
    `      COMPREPLY=(${compgen("--criterion --clear-criteria --format --policy --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    extension)",
    `      COMPREPLY=(${compgen(`${EXTENSION_LIFECYCLE_ACTIONS} ${EXTENSION_LIFECYCLE_FLAGS}`)})`,
    "      ;;",
    "    package|packages)",
    `      COMPREPLY=(${compgen(`${PACKAGE_LIFECYCLE_ACTIONS} ${PACKAGE_LIFECYCLE_FLAGS} ${UPGRADE_FLAGS}`)})`,
    "      ;;",
    "    comments)",
    `      COMPREPLY=(${compgen("--add --body --stdin --file --edit --delete --limit --full-history --if-absent --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    notes)",
    `      COMPREPLY=(${compgen("--add --add-json --stdin --file --edit --delete --limit --since --event-type --include-meta --full-history --if-absent --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    learnings)",
    `      COMPREPLY=(${compgen("--add --stdin --file --edit --delete --limit --full-history --if-absent --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    files)",
    `      COMPREPLY=(${compgen("discover lookup --add --add-glob --remove --migrate --list --apply --note --append-stable --validate-paths --scope --limit --offset --no-truncate --strict-read --explain --lines --decision-depth --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    docs)",
    `      COMPREPLY=(${compgen("--add --add-glob --remove --migrate --note --validate-paths --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    append)",
    `      COMPREPLY=(${compgen(APPEND_FLAGS)})`,
    "      ;;",
    "    deps)",
    `      COMPREPLY=(${compgen(DEPS_FLAGS)})`,
    "      ;;",
    "    graph)",
    `      COMPREPLY=(${compgen(`ancestors descendants predecessors successors paths impact analyze audit communities redundancy dominators slack centrality articulation plan index ${GRAPH_FLAGS}`)})`,
    "      ;;",
    "    test)",
    `      COMPREPLY=(${compgen("--add --add-json --remove --remove-index --list --run --match --only-index --only-last --background --timeout --progress --env-set --env-clear --shared-host-safe --pm-context --override-linked-pm-context --fail-on-context-mismatch --fail-on-skipped --fail-on-empty-test-run --require-assertions-for-pm --check-context --auto-pm-context --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    test-all)",
    `      COMPREPLY=(${compgen("--status --limit --offset --background --timeout --progress --env-set --env-clear --shared-host-safe --pm-context --override-linked-pm-context --fail-on-context-mismatch --fail-on-skipped --fail-on-empty-test-run --require-assertions-for-pm --check-context --auto-pm-context --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    test-runs)",
    `      COMPREPLY=(${compgen("list status logs stop resume --status --limit --stream --tail --force --author --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    validate)",
    `      COMPREPLY=(${compgen("--check-completeness --check-metadata --metadata-profile --check-resolution --check-lifecycle --check-stale-blockers --dependency-cycle-severity --parent-cycle-severity --check-files --scan-mode --include-pm-internals --verbose-file-lists --verbose-diagnostics --all-affected-ids --strict-exit --fail-on-warn --fix-hints --auto-fix --dry-run --fix-scope --prune-missing --check-history-drift --check-command-references --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    health)",
    `      COMPREPLY=(${compgen(HEALTH_FLAGS)})`,
    "      ;;",
    "    history)",
    '      if [[ $word_index -eq $cword ]]; then',
    `        COMPREPLY=(${compgen(`${HISTORY_FLAGS} ${HISTORY_LEAVES}`)})`,
    "      else",
    `        COMPREPLY=(${compgen(HISTORY_FLAGS)})`,
    "      fi",
    "      ;;",
    "    events)",
    `      COMPREPLY=(${compgen(EVENTS_FLAGS)})`,
    "      ;;",
    "    history-author-acknowledge)",
    `      COMPREPLY=(${compgen(`${HISTORY_AUTHOR_ACKNOWLEDGE_FLAGS} --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help`)})`,
    "      ;;",
    "    get)",
    `      COMPREPLY=(${compgen(GET_FLAGS)})`,
    "      ;;",
    "    schema)",
    '      if [[ "$prev" == "policy-mode" ]]; then',
    `        COMPREPLY=(${compgen("advise refuse")})`,
    "        return",
    "      fi",
    `      COMPREPLY=(${compgen(`${SCHEMA_SUBCOMMAND_CHOICES} --definition --policy --message --description --default-status --folder --alias --role --order --type --commands --cli-flag --required --required-on-create --no-allow-unset --required-types --infer --min-count --apply --to --migration-id --dry-run --author --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help`)})`,
    "      ;;",
    "    profile)",
    `      COMPREPLY=(${compgen("list show apply lint agile ops research --dry-run --author --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    plan)",
    `      COMPREPLY=(${compgen(`${PLAN_SUBCOMMANDS_LIST} ${PLAN_FLAGS}`)})`,
    "      ;;",
    "    contracts)",
    `      COMPREPLY=(${compgen(CONTRACTS_FLAGS)})`,
    "      ;;",
    "    gc)",
    `      COMPREPLY=(${compgen("--dry-run --scope --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")})`,
    "      ;;",
    "    stats)",
    `      COMPREPLY=(${compgen(STATS_FLAGS)})`,
    "      ;;",
    "    close-task)",
    `      COMPREPLY=(${compgen(CLOSE_TASK_MUTATION_FLAGS)})`,
    "      ;;",
    "    close)",
    `      COMPREPLY=(${compgen(CLOSE_MUTATION_FLAGS)})`,
    '      if [[ "$cmd" == "close" && $word_index -eq $cword ]]; then',
    `        COMPREPLY+=(${compgen(namespaceLeaves.close)})`,
    "      fi",
    "      ;;",
    "    close-many)",
    `      COMPREPLY=(${compgen(CLOSE_MANY_FLAGS)})`,
    "      ;;",
    "    release)",
    `      COMPREPLY=(${compgen(RELEASE_MUTATION_FLAGS)})`,
    "      ;;",
    "    delete)",
    `      COMPREPLY=(${compgen(DELETE_MUTATION_FLAGS)})`,
    "      ;;",
    "    claim)",
    `      COMPREPLY=(${compgen(CLAIM_MUTATION_FLAGS)})`,
    "      ;;",
    "    start-task|pause-task)",
    `      COMPREPLY=(${compgen(MUTATION_FLAGS)})`,
    "      ;;",
    "    meet|event)",
    `      COMPREPLY=(${compgen(MEET_FLAGS)})`,
    "      ;;",
    "    remind)",
    `      COMPREPLY=(${compgen(REMIND_FLAGS)})`,
    "      ;;",
    "    completion)",
    `      COMPREPLY=(${compgen(COMPLETION_SHELL_CHOICES)})`,
    "      ;;",
    "    templates)",
    `      COMPREPLY=(${compgen("save list show")})`,
    "      ;;",
    "    *)",
    `      COMPREPLY=(${compgen(GLOBAL_FLAGS)})`,
    "      ;;",
    "  esac",
    '  if [[ $word_index -eq $cword ]]; then',
    '    case "$command_path" in',
    ...Object.entries(namespaceLeaves).filter(([prefix]) => ["item", "workspace", "search"].includes(prefix.split(" ")[0])).map(([prefix, leaves]) => `      "${prefix}") COMPREPLY+=(${compgen(leaves)}) ;;`),
    '    esac',
    '  fi',
    '  if [[ "$cmd" == "comments" || "$cmd" == "notes" || "$cmd" == "learnings" ]]; then',
    `    COMPREPLY+=(${compgen("--text")})`,
    "  fi",
    "  return 0",
    "}",
    "",
    "complete -F _pm_completion pm",
  ].join("\n");
}
