/**
 * @module sdk/completion/bash
 * Renders Bash completion from shared command contracts and runtime schema.
 */
import {
  PM_NAMESPACED_COMMAND_ALIASES
} from "../cli-contracts.js";
import type { CompletionRuntimeConfig } from "./shared.js";
import { AGGREGATE_FLAGS,ALL_COMMANDS,APPEND_FLAGS,CALENDAR_FLAGS,CLAIM_MUTATION_FLAGS,CLOSE_MANY_FLAGS,CLOSE_MUTATION_FLAGS,CLOSE_TASK_MUTATION_FLAGS,COMPLETION_SHELL_CHOICES,CONTEXT_FLAGS,CONTRACTS_FLAGS,COPY_FLAGS,CREATE_FLAGS,DELETE_MUTATION_FLAGS,DEPS_FLAGS,DUPLICATES_FLAGS,EVENTS_FLAGS,EXTENSION_LIFECYCLE_ACTIONS,EXTENSION_LIFECYCLE_FLAGS,FOCUS_FLAGS,GET_FLAGS,GLOBAL_COMPLETION_INLINE_PATTERNS,GLOBAL_COMPLETION_SWITCH_PATTERNS,GLOBAL_COMPLETION_VALUE_PATTERNS,GLOBAL_FLAGS,GRAPH_FLAGS,GUIDE_FLAGS,GUIDE_TOPIC_CHOICES,HEALTH_FLAGS,HISTORY_AUTHOR_ACKNOWLEDGE_FLAGS,HISTORY_FLAGS,HISTORY_LEAVES,HISTORY_OPERATION_FLAGS,INIT_FLAGS,LIST_FLAGS,MEET_FLAGS,MUTATION_FLAGS,NAMESPACE_NOUNS,NAMESPACE_PREFIXES,NEXT_FLAGS,PACKAGE_LIFECYCLE_ACTIONS,PACKAGE_LIFECYCLE_FLAGS,PLAN_FLAGS,PLAN_SUBCOMMANDS_LIST,RELEASE_MUTATION_FLAGS,REMIND_FLAGS,SCHEMA_SUBCOMMAND_CHOICES,SEARCH_FLAGS,STATS_FLAGS,UPDATE_FLAGS,UPDATE_MANY_FLAGS,UPGRADE_FLAGS,completionNamespaceLeaves,completionStatusValues,completionTypeValues,joinCompletionValues,mergeFlagStrings,shellDoubleQuote } from "./shared.js";

/** Emit a TTL-cached Bash status or type resolver with a source-escaped fallback when the helper returns no choices. */
function renderBashDynamicChoiceResolver(
  kind: "status" | "type",
  command: "completion-statuses" | "completion-types",
  fallback: string,
): string[] {
  const envKind = kind.toUpperCase();
  const cacheVar = `PM_COMPLETION_${envKind}_CACHE`;
  const cacheTsVar = `PM_COMPLETION_${envKind}_CACHE_TS`;
  const ttlVar = `PM_COMPLETION_${envKind}_TTL`;
  const escapedFallback = shellDoubleQuote(fallback);
  return [
    `_pm_completion_${kind}_choices() {`,
    "  local now ttl cache_ts resolved",
    '  now="$(date +%s 2>/dev/null || echo 0)"',
    `  ttl="\${${ttlVar}:-120}"`,
    `  cache_ts="\${${cacheTsVar}:-0}"`,
    `  if [[ -n "\${${cacheVar}:-}" && "$now" -ne 0 && $((now - cache_ts)) -lt "$ttl" ]]; then`,
    `    printf '%s\\n' "$${cacheVar}"`,
    "    return 0",
    "  fi",
    `  resolved="$(pm ${command} 2>/dev/null)"`,
    '  if [[ -z "$resolved" ]]; then',
    `    resolved="${escapedFallback}"`,
    "  fi",
    `  ${cacheVar}="$resolved"`,
    `  ${cacheTsVar}="$now"`,
    `  printf '%s\\n' "$${cacheVar}"`,
    "}",
  ];
}

/** Render Bash 3.2-compatible completion with literal prefix matching of schema and command choices. */
export function generateBashScript(
  itemTypes: string[] = [],
  tags: string[] = [],
  eagerTagExpansion = false,
  runtime: CompletionRuntimeConfig = {},
): string {
  const namespaceLeaves = completionNamespaceLeaves(runtime);
  const cmds = ALL_COMMANDS.join(" ");
  const useDynamicTypeExpansion = itemTypes.length === 0;
  const typeValues = completionTypeValues(itemTypes, runtime);
  const statusValues = completionStatusValues(runtime);
  const tagValues = joinCompletionValues(tags);
  const listFlags = mergeFlagStrings(LIST_FLAGS, runtime.command_flags?.list);
  const createFlags = mergeFlagStrings(
    CREATE_FLAGS,
    runtime.command_flags?.create,
  );
  const updateFlags = mergeFlagStrings(
    UPDATE_FLAGS,
    runtime.command_flags?.update,
  );
  const updateManyFlags = mergeFlagStrings(
    UPDATE_MANY_FLAGS,
    runtime.command_flags?.["update-many"],
  );
  const searchFlags = mergeFlagStrings(
    SEARCH_FLAGS,
    runtime.command_flags?.search,
  );
  const calendarFlags = mergeFlagStrings(
    CALENDAR_FLAGS,
    runtime.command_flags?.calendar,
  );
  const contextFlags = mergeFlagStrings(
    CONTEXT_FLAGS,
    runtime.command_flags?.context,
  );
  const useEagerTagExpansion = eagerTagExpansion || tags.length > 0;
  // Note: "${...}" inside regular (non-template) strings are literal characters,
  // not JS interpolation. Only backtick template literals interpolate ${...}.
  /** Quote static choices once when embedding them in an invocation of the literal Bash matcher. */
  const matchWords = (values: string): string =>
    `_pm_completion_add_matches "${shellDoubleQuote(values)}"`;
  return [
    "# bash completion for pm",
    "# Source this file or add 'eval \"$(pm completion bash)\"' to ~/.bashrc",
    "",
    ...(useDynamicTypeExpansion
      ? [
          ...renderBashDynamicChoiceResolver(
            "type",
            "completion-types",
            typeValues,
          ),
          "",
        ]
      : []),
    ...renderBashDynamicChoiceResolver(
      "status",
      "completion-statuses",
      statusValues,
    ),
    "",
    "# Treat choices as data: no eval, compgen expansion, or filename globbing.",
    "_pm_completion_add_matches() {",
    "  local line value quoted",
    "  local -a values",
    "  while IFS= read -r line; do",
    "    read -r -a values <<< \"$line\"",
    '    for value in "${values[@]}"; do',
    "      [[ \"$value\" == \"$cur\"* ]] || continue",
    "      case \"$value\" in",
    "        *[!a-zA-Z0-9_.,:/@%+=-]*)",
    "          quoted=${value//\\'/\\'\\\\\\'\\'}",
    "          COMPREPLY+=(\"'$quoted'\")",
    "          ;;",
    "        *) COMPREPLY+=(\"$value\") ;;",
    "      esac",
    "    done",
    "  done <<< \"$1\"",
    "}",
    "",
    "_pm_completion() {",
    "  local cur prev words cword",
    "  COMPREPLY=()",
    "  # Refuse ambiguous shell quoting before _init_completion can dequote it.",
    "  case \"${COMP_WORDS[COMP_CWORD]}\" in",
    "    *\"'\"*|*'\"'*|*'`'*|*'\\'*) return 0 ;;",
    "  esac",
    "  _init_completion 2>/dev/null || {",
    '    cur="${COMP_WORDS[COMP_CWORD]}"',
    '    prev="${COMP_WORDS[COMP_CWORD-1]}"',
    "    cword=$COMP_CWORD",
    "  }",
    "",
    "  if [[ $cword -eq 1 ]]; then",
    `    ${matchWords(cmds)}`,
    "    return 0",
    "  fi",
    "",
    '  if [[ "$prev" == "--type" ]]; then',
    useDynamicTypeExpansion
      ? '    _pm_completion_add_matches "$(_pm_completion_type_choices)"'
      : `    ${matchWords(typeValues)}`,
    "    return 0",
    "  fi",
    "",
    '  if [[ "$prev" == "--status" ]]; then',
    '    _pm_completion_add_matches "$(_pm_completion_status_choices)"',
    "    return 0",
    "  fi",
    "",
    ...(useEagerTagExpansion
      ? [
          '  if [[ ( "$prev" == "--tag" || "$prev" == "--tags" ) && ! ( ( "${COMP_WORDS[1]}" == "package" || "${COMP_WORDS[1]}" == "packages" ) && "${COMP_WORDS[2]}" == "upgrade" ) ]]; then',
          `    ${matchWords(tagValues)}`,
          "    return 0",
          "  fi",
        ]
      : [
          '  if [[ ( "$prev" == "--tag" || "$prev" == "--tags" ) && ! ( ( "${COMP_WORDS[1]}" == "package" || "${COMP_WORDS[1]}" == "packages" ) && "${COMP_WORDS[2]}" == "upgrade" ) ]]; then',
          "    local now ttl cache_ts tag_values",
          '    now="$(date +%s 2>/dev/null || echo 0)"',
          '    ttl="${PM_COMPLETION_TAG_TTL:-120}"',
          '    cache_ts="${PM_COMPLETION_TAG_CACHE_TS:-0}"',
          '    tag_values="${PM_COMPLETION_TAG_CACHE:-}"',
          '    if [[ -z "$tag_values" || "$now" -eq 0 || $((now - cache_ts)) -ge "$ttl" ]]; then',
          '      tag_values="$(pm completion-tags 2>/dev/null)"',
          '      PM_COMPLETION_TAG_CACHE="$tag_values"',
          '      PM_COMPLETION_TAG_CACHE_TS="$now"',
          "    fi",
          '    _pm_completion_add_matches "$tag_values"',
          "    return 0",
          "  fi",
        ]),
    "",
    '  if [[ "$prev" == "--tag" && ( ( "${COMP_WORDS[1]}" == "package" || "${COMP_WORDS[1]}" == "packages" ) && "${COMP_WORDS[2]}" == "upgrade" ) ]]; then',
    "    COMPREPLY=()",
    "    return 0",
    "  fi",
    "",
    '  local cmd="" command_path="" word_index=1 word',
    "  while (( word_index < cword )); do",
    '    word="${COMP_WORDS[word_index]}"',
    '    case "${word//_/-}" in',
    `      ${GLOBAL_COMPLETION_VALUE_PATTERNS}) (( word_index += 2 )); continue ;;`,
    `      ${GLOBAL_COMPLETION_INLINE_PATTERNS}|${GLOBAL_COMPLETION_SWITCH_PATTERNS}) (( word_index++ )); continue ;;`,
    "      --) break ;;",
    "    esac",
    '    if [[ -z "$cmd" ]]; then',
    '      cmd="$word"',
    '      [[ "$cmd" == "ctx" ]] && cmd="context"',
    '      command_path="$cmd"',
    `      case "$cmd" in ${NAMESPACE_NOUNS.join("|")}) ;; *) break ;; esac`,
    "    else",
    '      case "$command_path $word" in',
    ...PM_NAMESPACED_COMMAND_ALIASES.map((entry) => `        "${entry.canonical}") cmd="${entry.alias}"; command_path="${entry.canonical}" ;;`),
    '        *) break ;;',
    "      esac",
    `      case "$command_path" in ${NAMESPACE_PREFIXES.map((prefix) => `"${prefix}"`).join("|")}) ;; *) (( word_index++ )); break ;; esac`,
    "    fi",
    "    (( word_index++ ))",
    "  done",
    '  case "$cmd" in',
    ...HISTORY_OPERATION_FLAGS.flatMap((entry) => [
      `    ${entry.alias})`,
      `      ${matchWords(entry.flags)}`,
      "      return 0",
      "      ;;",
    ]),
    "    list)",
    `      ${matchWords(listFlags)}`,
    "      ;;",
    "    aggregate)",
    `      ${matchWords(AGGREGATE_FLAGS)}`,
    "      ;;",
    "    duplicates)",
    `      ${matchWords(DUPLICATES_FLAGS)}`,
    "      ;;",
    "    create)",
    `      ${matchWords(createFlags)}`,
    "      ;;",
    "    copy)",
    `      ${matchWords(COPY_FLAGS)}`,
    "      ;;",
    "    focus)",
    `      ${matchWords(FOCUS_FLAGS)}`,
    "      ;;",
    "    update)",
    `      ${matchWords(updateFlags)}`,
    '      if [[ $word_index -eq $cword ]]; then',
    `        ${matchWords(namespaceLeaves.update)}`,
    "      fi",
    "      ;;",
    "    update-many)",
    `      ${matchWords(updateManyFlags)}`,
    "      ;;",
    "    calendar|cal)",
    `      ${matchWords(calendarFlags)}`,
    "      ;;",
    "    context|ctx)",
    `      ${matchWords(contextFlags)}`,
    '      if [[ $word_index -eq $cword ]]; then',
    `        ${matchWords(namespaceLeaves.context)}`,
    "      fi",
    "      ;;",
    "    ops)",
    `      ${matchWords(`${GLOBAL_FLAGS} ${namespaceLeaves.ops}`)}`,
    "      ;;",
    "    next)",
    `      ${matchWords(NEXT_FLAGS)}`,
    "      ;;",
    "    guide)",
    `      ${matchWords(`${GUIDE_FLAGS} ${GUIDE_TOPIC_CHOICES}`)}`,
    "      ;;",
    "    search)",
    `      ${matchWords(searchFlags)}`,
    "      ;;",
    "    reindex)",
    `      ${matchWords("--mode --progress --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    init)",
    `      ${matchWords(`${INIT_FLAGS} --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help`)}`,
    "      ;;",
    "    config)",
    `      ${matchWords("--criterion --clear-criteria --format --policy --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    extension)",
    `      ${matchWords(`${EXTENSION_LIFECYCLE_ACTIONS} ${EXTENSION_LIFECYCLE_FLAGS}`)}`,
    "      ;;",
    "    package|packages)",
    `      ${matchWords(`${PACKAGE_LIFECYCLE_ACTIONS} ${PACKAGE_LIFECYCLE_FLAGS} ${UPGRADE_FLAGS}`)}`,
    "      ;;",
    "    comments)",
    `      ${matchWords("--add --body --stdin --file --edit --delete --limit --full-history --if-absent --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    notes)",
    `      ${matchWords("--add --add-json --stdin --file --edit --delete --limit --since --event-type --include-meta --full-history --if-absent --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    learnings)",
    `      ${matchWords("--add --stdin --file --edit --delete --limit --full-history --if-absent --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    files)",
    `      ${matchWords("discover lookup --add --add-glob --remove --migrate --list --apply --note --append-stable --validate-paths --scope --limit --offset --no-truncate --strict-read --explain --lines --decision-depth --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    docs)",
    `      ${matchWords("--add --add-glob --remove --migrate --note --validate-paths --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    append)",
    `      ${matchWords(APPEND_FLAGS)}`,
    "      ;;",
    "    deps)",
    `      ${matchWords(DEPS_FLAGS)}`,
    "      ;;",
    "    graph)",
    `      ${matchWords(`ancestors descendants predecessors successors paths impact analyze audit communities redundancy dominators slack centrality articulation plan index ${GRAPH_FLAGS}`)}`,
    "      ;;",
    "    test)",
    `      ${matchWords("--add --add-json --remove --remove-index --list --run --match --only-index --only-last --background --timeout --progress --env-set --env-clear --shared-host-safe --pm-context --override-linked-pm-context --fail-on-context-mismatch --fail-on-skipped --fail-on-empty-test-run --require-assertions-for-pm --check-context --auto-pm-context --author --message --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    test-all)",
    `      ${matchWords("--status --limit --offset --background --timeout --progress --env-set --env-clear --shared-host-safe --pm-context --override-linked-pm-context --fail-on-context-mismatch --fail-on-skipped --fail-on-empty-test-run --require-assertions-for-pm --check-context --auto-pm-context --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    test-runs)",
    `      ${matchWords("list status logs stop resume --status --limit --stream --tail --force --author --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    validate)",
    `      ${matchWords("--check-completeness --check-metadata --metadata-profile --check-resolution --check-lifecycle --check-stale-blockers --dependency-cycle-severity --parent-cycle-severity --check-files --scan-mode --include-pm-internals --verbose-file-lists --verbose-diagnostics --all-affected-ids --strict-exit --fail-on-warn --fix-hints --auto-fix --dry-run --fix-scope --prune-missing --check-history-drift --check-command-references --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    health)",
    `      ${matchWords(HEALTH_FLAGS)}`,
    "      ;;",
    "    history)",
    '      if [[ $word_index -eq $cword ]]; then',
    `        ${matchWords(`${HISTORY_FLAGS} ${HISTORY_LEAVES}`)}`,
    "      else",
    `        ${matchWords(HISTORY_FLAGS)}`,
    "      fi",
    "      ;;",
    "    events)",
    `      ${matchWords(EVENTS_FLAGS)}`,
    "      ;;",
    "    history-author-acknowledge)",
    `      ${matchWords(`${HISTORY_AUTHOR_ACKNOWLEDGE_FLAGS} --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help`)}`,
    "      ;;",
    "    get)",
    `      ${matchWords(GET_FLAGS)}`,
    "      ;;",
    "    schema)",
    '      if [[ "$prev" == "policy-mode" ]]; then',
    `        ${matchWords("advise refuse")}`,
    "        return",
    "      fi",
    `      ${matchWords(`${SCHEMA_SUBCOMMAND_CHOICES} --definition --policy --message --description --default-status --folder --alias --role --order --type --commands --cli-flag --required --required-on-create --no-allow-unset --required-types --infer --min-count --apply --to --migration-id --dry-run --author --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help`)}`,
    "      ;;",
    "    profile)",
    `      ${matchWords("list show apply lint agile ops research --dry-run --author --force --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    plan)",
    `      ${matchWords(`${PLAN_SUBCOMMANDS_LIST} ${PLAN_FLAGS}`)}`,
    "      ;;",
    "    contracts)",
    `      ${matchWords(CONTRACTS_FLAGS)}`,
    "      ;;",
    "    gc)",
    `      ${matchWords("--dry-run --scope --json --quiet --no-changed-fields --pm-path --path --no-extensions --no-pager --profile --help")}`,
    "      ;;",
    "    stats)",
    `      ${matchWords(STATS_FLAGS)}`,
    "      ;;",
    "    close-task)",
    `      ${matchWords(CLOSE_TASK_MUTATION_FLAGS)}`,
    "      ;;",
    "    close)",
    `      ${matchWords(CLOSE_MUTATION_FLAGS)}`,
    '      if [[ "$cmd" == "close" && $word_index -eq $cword ]]; then',
    `        ${matchWords(namespaceLeaves.close)}`,
    "      fi",
    "      ;;",
    "    close-many)",
    `      ${matchWords(CLOSE_MANY_FLAGS)}`,
    "      ;;",
    "    release)",
    `      ${matchWords(RELEASE_MUTATION_FLAGS)}`,
    "      ;;",
    "    delete)",
    `      ${matchWords(DELETE_MUTATION_FLAGS)}`,
    "      ;;",
    "    claim)",
    `      ${matchWords(CLAIM_MUTATION_FLAGS)}`,
    "      ;;",
    "    start-task|pause-task)",
    `      ${matchWords(MUTATION_FLAGS)}`,
    "      ;;",
    "    meet|event)",
    `      ${matchWords(MEET_FLAGS)}`,
    "      ;;",
    "    remind)",
    `      ${matchWords(REMIND_FLAGS)}`,
    "      ;;",
    "    completion)",
    `      ${matchWords(COMPLETION_SHELL_CHOICES)}`,
    "      ;;",
    "    templates)",
    `      ${matchWords("save list show")}`,
    "      ;;",
    "    *)",
    `      ${matchWords(GLOBAL_FLAGS)}`,
    "      ;;",
    "  esac",
    '  if [[ $word_index -eq $cword ]]; then',
    '    case "$command_path" in',
    ...Object.entries(namespaceLeaves).filter(([prefix]) => ["item", "workspace", "search"].includes(prefix.split(" ")[0])).map(([prefix, leaves]) => `      "${prefix}") ${matchWords(leaves)} ;;`),
    '    esac',
    '  fi',
    '  if [[ "$cmd" == "comments" || "$cmd" == "notes" || "$cmd" == "learnings" ]]; then',
    `    ${matchWords("--text")}`,
    "  fi",
    "  return 0",
    "}",
    "",
    "complete -F _pm_completion pm",
  ].join("\n");
}
