import { defineConfig } from "vitest/config";

export default defineConfig({
  test: {
    include: ["tests/**/*.spec.ts"],
    testTimeout: 30_000,
    hookTimeout: 30_000,
    coverage: {
      provider: "v8",
      reporter: ["text", "json-summary", "html"],
      include: [
        "src/command-types.ts",
        "src/constants.ts",
        "src/cli/commands/init.ts",
        "src/cli/commands/create.ts",
        "src/cli/commands/close.ts",
        "src/cli/commands/delete.ts",
        "src/cli/commands/append.ts",
        "src/cli/commands/activity.ts",
        "src/cli/commands/beads.ts",
        "src/cli/commands/claim.ts",
        "src/cli/commands/comments.ts",
        "src/cli/commands/docs.ts",
        "src/cli/commands/files.ts",
        "src/cli/commands/gc.ts",
        "src/cli/commands/get.ts",
        "src/cli/commands/health.ts",
        "src/cli/commands/history.ts",
        "src/cli/commands/list.ts",
        "src/cli/commands/search.ts",
        "src/cli/commands/reindex.ts",
        "src/cli/commands/restore.ts",
        "src/cli/commands/stats.ts",
        "src/cli/commands/test.ts",
        "src/cli/commands/test-all.ts",
        "src/cli/commands/update.ts",
        "src/cli/commands/index.ts",
        "src/core/extensions/builtins.ts",
        "src/core/extensions/index.ts",
        "src/core/extensions/loader.ts",
        "src/core/fs/fs-utils.ts",
        "src/core/fs/index.ts",
        "src/core/history/history.ts",
        "src/core/history/index.ts",
        "src/core/item/id.ts",
        "src/core/item/item-format.ts",
        "src/core/item/parse.ts",
        "src/core/item/index.ts",
        "src/core/lock/lock.ts",
        "src/core/lock/index.ts",
        "src/core/output/output.ts",
        "src/core/shared/command-types.ts",
        "src/core/search/cache.ts",
        "src/core/search/providers.ts",
        "src/core/search/vector-stores.ts",
        "src/core/shared/index.ts",
        "src/core/shared/constants.ts",
        "src/core/shared/errors.ts",
        "src/core/shared/serialization.ts",
        "src/core/shared/time.ts",
        "src/core/store/index.ts",
        "src/core/store/item-store.ts",
        "src/core/store/paths.ts",
        "src/core/store/settings.ts",
        "src/errors.ts",
        "src/fs-utils.ts",
        "src/history.ts",
        "src/id.ts",
        "src/item-format.ts",
        "src/item-store.ts",
        "src/lock.ts",
        "src/output.ts",
        "src/parse.ts",
        "src/paths.ts",
        "src/serialization.ts",
        "src/settings.ts",
        "src/time.ts",
        "src/types.ts",
        "src/extensions/builtins/beads/index.ts",
        "src/extensions/builtins/todos/index.ts",
        "src/extensions/builtins/todos/import-export.ts",
        "src/types/index.ts",
      ],
      thresholds: {
        lines: 100,
        branches: 100,
        functions: 100,
        statements: 100,
      },
    },
  },
});
