import { defineConfig } from "vitest/config";

const coverageReporters = process.env.CI
  ? (["text", "json-summary"] as const)
  : (["text", "json-summary", "html"] as const);

export default defineConfig({
  cacheDir: ".cache/vitest",
  test: {
    include: ["tests/**/*.spec.ts"],
    testTimeout: 30_000,
    hookTimeout: 30_000,
    coverage: {
      provider: "v8",
      reporter: coverageReporters,
      include: [
        "packages/pm-beads/extensions/beads/runtime.js",
        "packages/pm-search-advanced/extensions/search-advanced/runtime.js",
        "packages/pm-todos/extensions/todos/runtime.js",
        "src/command-types.ts",
        "src/constants.ts",
        "src/cli/commands/init.ts",
        "src/cli/commands/create.ts",
        "src/cli/commands/close.ts",
        "src/cli/commands/delete.ts",
        "src/cli/commands/append.ts",
        "src/cli/commands/activity.ts",
        "src/cli/commands/completion.ts",
        "src/cli/commands/claim.ts",
        "src/cli/commands/annotation-command.ts",
        "src/cli/commands/comments.ts",
        "src/cli/commands/notes.ts",
        "src/cli/commands/learnings.ts",
        "src/cli/commands/config.ts",
        "src/cli/commands/contracts.ts",
        "src/cli/commands/context.ts",
        "src/cli/commands/deps.ts",
        "src/cli/commands/docs.ts",
        "src/cli/commands/extension.ts",
        "src/cli/commands/files.ts",
        "src/cli/commands/gc.ts",
        "src/cli/commands/get.ts",
        "src/cli/commands/health.ts",
        "src/cli/commands/history.ts",
        "src/cli/commands/list.ts",
        "src/cli/commands/calendar.ts",
        "src/cli/commands/search.ts",
        "src/cli/commands/reindex.ts",
        "src/cli/commands/restore.ts",
        "src/cli/commands/schema.ts",
        "src/cli/commands/stats.ts",
        "src/cli/commands/test.ts",
        "src/cli/commands/test-all.ts",
        "src/cli/commands/update.ts",
        "src/cli/commands/upgrade.ts",
        "src/cli/commands/validate.ts",
        "src/cli/commands/index.ts",
        "src/cli/commands/legacy-none-tokens.ts",
        "src/cli/commands/linked-artifacts.ts",
        "src/cli/commands/linked-test-parsers.ts",
        "src/cli/commands/recurrence-parsers.ts",
        "src/cli/commands/repeatable-metadata-parsers.ts",
        "src/cli/extension-command-options.ts",
        "src/core/config/positional-value.ts",
        "src/core/diagnostics/remediation.ts",
        "src/core/extensions/index.ts",
        "src/core/extensions/item-fields.ts",
        "src/core/extensions/loader.ts",
        "src/core/extensions/runtime-registrations.ts",
        "src/core/fs/fs-utils.ts",
        "src/core/fs/index.ts",
        "src/core/fs/path-utils.ts",
        "src/core/history/drift-scan.ts",
        "src/core/history/history.ts",
        "src/core/history/history-diff.ts",
        "src/core/history/history-storage-stats.ts",
        "src/core/history/history-rewrite.ts",
        "src/core/history/history-stream-policy.ts",
        "src/core/history/replay.ts",
        "src/core/history/index.ts",
        "src/core/item/id.ts",
        "src/core/item/item-format.ts",
        "src/core/item/item-record.ts",
        "src/core/item/item-type-definition.ts",
        "src/core/item/type-synonyms.ts",
        "src/core/item/sprint-release-format.ts",
        "src/core/item/parse.ts",
        "src/core/item/priority.ts",
        "src/core/item/status.ts",
        "src/core/item/status-filter.ts",
        "src/core/item/toon-decode.ts",
        "src/core/item/index.ts",
        "src/core/checkpoint/mutation-checkpoint.ts",
        "src/core/lock/lock.ts",
        "src/core/lock/lock-gc.ts",
        "src/core/lock/index.ts",
        "src/core/output/output.ts",
        "src/core/output/mutation-projection.ts",
        "src/core/packages/manifest.ts",
        "src/core/schema/item-types-file.ts",
        "src/core/schema/status-defs-file.ts",
        "src/core/schema/type-workflows.ts",
        "src/core/shared/author.ts",
        "src/core/shared/command-types.ts",
        "src/core/config/nested-settings.ts",
        "src/core/search/cache.ts",
        "src/core/search/background-refresh.ts",
        "src/core/search/corpus.ts",
        "src/core/search/embedding-batches.ts",
        "src/core/search/http-client.ts",
        "src/core/search/providers.ts",
        "src/core/search/semantic-defaults.ts",
        "src/core/search/staleness.ts",
        "src/core/search/vectorization-metadata.ts",
        "src/core/search/vector-stores.ts",
        "src/core/shared/html-entity-decode.ts",
        "src/core/shared/index.ts",
        "src/core/shared/primitives.ts",
        "src/core/shared/constants.ts",
        "src/core/shared/conflict-markers.ts",
        "src/core/shared/errors.ts",
        "src/core/shared/lazy-module.ts",
        "src/core/shared/levenshtein.ts",
        "src/core/shared/option-alias-visibility.ts",
        "src/core/shared/serial-queue.ts",
        "src/core/shared/serialization.ts",
        "src/core/shared/split-comma-list.ts",
        "src/core/shared/time.ts",
        "src/core/store/index.ts",
        "src/core/store/item-format-migration.ts",
        "src/core/store/item-store.ts",
        "src/core/store/paths.ts",
        "src/core/store/settings.ts",
        "src/core/store/settings-validator.ts",
        "src/errors.ts",
        "src/fs-utils.ts",
        "src/history.ts",
        "src/id.ts",
        "src/item-format.ts",
        "src/item-store.ts",
        "src/lock.ts",
        "src/output.ts",
        "src/parse.ts",
        "src/paths.ts",
        "src/serialization.ts",
        "src/settings.ts",
        "src/time.ts",
        "src/types.ts",
        "src/sdk/errors.ts",
        "src/sdk/index.ts",
        "src/sdk/package-import-adapters.ts",
        "src/sdk/package-runtime-options.ts",
        "src/sdk/runtime.ts",
        "src/sdk/testing.ts",
        "src/types/index.ts",
      ],
      exclude: [
        "packages/pm-todos/extensions/todos/runtime.js",
        "src/cli/commands/activity.ts",
        "src/cli/commands/append.ts",
        "src/cli/commands/calendar.ts",
        "src/cli/commands/close.ts",
        "src/cli/commands/comments.ts",
        "src/cli/commands/config.ts",
        "src/cli/commands/context.ts",
        "src/cli/commands/contracts.ts",
        "src/cli/commands/create.ts",
        "src/cli/commands/deps.ts",
        "src/cli/commands/docs.ts",
        "src/cli/commands/extension.ts",
        "src/cli/commands/files.ts",
        "src/cli/commands/health.ts",
        "src/cli/commands/history.ts",
        "src/cli/commands/init.ts",
        "src/cli/commands/learnings.ts",
        "src/cli/commands/list.ts",
        "src/cli/commands/notes.ts",
        "src/cli/commands/reindex.ts",
        "src/cli/commands/restore.ts",
        "src/cli/commands/schema.ts",
        "src/cli/commands/search.ts",
        "src/cli/commands/stats.ts",
        "src/cli/commands/test-all.ts",
        "src/cli/commands/test.ts",
        "src/cli/commands/update.ts",
        "src/cli/commands/upgrade.ts",
        "src/cli/commands/validate.ts",
        "src/cli/extension-command-options.ts",
        "src/core/extensions/index.ts",
        "src/core/extensions/item-fields.ts",
        "src/core/extensions/loader.ts",
        "src/core/extensions/runtime-registrations.ts",
        "src/core/history/history.ts",
        "src/core/item/item-format.ts",
        "src/core/item/parse.ts",
        "src/core/item/sprint-release-format.ts",
        "src/core/lock/lock.ts",
        "src/core/output/output.ts",
        "src/core/search/cache.ts",
        "src/core/search/background-refresh.ts",
        "src/core/search/semantic-defaults.ts",
        "src/core/shared/conflict-markers.ts",
        "src/core/shared/time.ts",
        "src/core/store/item-store.ts",
        "src/core/store/settings.ts",
      ],
      thresholds: {
        lines: 100,
        branches: 100,
        functions: 100,
        statements: 100,
      },
    },
  },
});
