import { describe, expect, it, vi } from "vitest";

import { createScriptHarness } from "../../helpers/scriptModule";

interface GeneratorModule {
  main: () => Promise<void>;
}

const harness = createScriptHarness();

describe("gen-plugin-mcp-wrappers", () => {
  it("writes both plugin wrappers in write mode", async () => {
    const generated = new Map<string, string>();
    vi.doMock("node:fs/promises", () => ({
      readFile: vi.fn(async (target: string) => generated.get(String(target)) ?? ""),
      writeFile: vi.fn(async (target: string, content: string) => {
        generated.set(String(target), String(content));
      }),
    }));
    const logSpy = vi.spyOn(console, "log").mockImplementation(() => {});
    process.argv = ["node", "/nonmatching/runner"];
    const mod = await harness.importModule<GeneratorModule>("scripts/gen-plugin-mcp-wrappers.mjs");
    await mod.main();
    expect(logSpy.mock.calls.some((call) => String(call[0]).includes("Wrote"))).toBe(true);
    expect(generated.size).toBe(2);
    for (const content of generated.values()) {
      expect(content).toContain("This file is auto-generated by scripts/gen-plugin-mcp-wrappers.mjs");
      expect(content).toContain("Do not edit directly.");
      expect(content).toContain('shell: process.platform === "win32"');
      expect(content).toContain("let url;");
      expect(content).toContain("url = new URL(target);");
      expect(content).toContain("let filePath;");
      expect(content).toContain("filePath = fileURLToPath(url);");
      expect(content).toContain("return false;");
      expect(content).toMatch(/(?:exists|canRead)\(filePath\)/);
    }
  });

  it("reports in-sync when --check finds matching wrapper content", async () => {
    const generated = new Map<string, string>();
    vi.doMock("node:fs/promises", () => ({
      readFile: vi.fn(async (target: string) => generated.get(String(target)) ?? ""),
      writeFile: vi.fn(async (target: string, content: string) => {
        generated.set(String(target), String(content));
      }),
    }));
    vi.spyOn(console, "log").mockImplementation(() => {});
    process.argv = ["node", "/nonmatching/runner"];
    const writeMod = await harness.importModule<GeneratorModule>("scripts/gen-plugin-mcp-wrappers.mjs");
    await writeMod.main();

    const syncLog = vi.spyOn(console, "log").mockImplementation(() => {});
    process.argv = ["node", "/nonmatching/runner", "--check"];
    const checkMod = await harness.importModule<GeneratorModule>("scripts/gen-plugin-mcp-wrappers.mjs");
    await checkMod.main();
    expect(syncLog.mock.calls.some((call) => String(call[0]).includes("in sync"))).toBe(true);
  });

  it("reports drift and exits 1 when a target read fails under --check", async () => {
    vi.doMock("node:fs/promises", () => ({
      readFile: vi.fn(async () => {
        throw new Error("missing");
      }),
      writeFile: vi.fn(async () => {}),
    }));
    const errorSpy = vi.spyOn(console, "error").mockImplementation(() => {});
    vi.spyOn(console, "log").mockImplementation(() => {});
    const exit = harness.mockProcessExit();
    process.argv = ["node", "/nonmatching/runner", "--check"];
    const mod = await harness.importModule<GeneratorModule>("scripts/gen-plugin-mcp-wrappers.mjs");
    await expect(mod.main()).rejects.toThrow("EXIT:1");
    expect(errorSpy.mock.calls.some((call) => String(call[0]).includes("Out of sync"))).toBe(true);
    exit.mockRestore();
  });
});
