/**
 * @module sdk/graph
 *
 * Public workspace graph toolkit: one-pass relationship assembly with
 * missing-reference governance, registry-semantics traversal (hierarchy,
 * execution order, bounded path enumeration), and the policy-aware
 * relationship audit. Everything here layers on the dependency-free kernel in
 * `sdk/relationships` and is safe for CLI, MCP, extension, and non-PM callers.
 */
export {
  computeRelationshipDominators,
  detectRelationshipCommunities,
  findRedundantRelationshipEdges,
  forEachMatchedRelationshipEdge,
  type GraphCommunityOptions,
  type GraphDominatorOptions,
  type GraphRedundancyOptions,
  type RedundantRelationshipEdge,
  type RelationshipCommunity,
  type RelationshipCommunityAnalysis,
  type RelationshipDominatorAnalysis,
  type RelationshipDominatorRow,
} from "./analytics.js";
export {
  computeRelationshipCentrality,
  findRelationshipCutStructure,
  type GraphCentralityOptions,
  type GraphCutStructureOptions,
  type RelationshipBridge,
  type RelationshipCentralityAnalysis,
  type RelationshipCentralityRow,
  type RelationshipCutStructure,
} from "./centrality.js";
export {
  createRelationshipGraphSnapshot,
  federateRelationshipGraphSnapshots,
  loadRelationshipGraphAdapter,
  MemoryRelationshipGraphAdapter,
  parseRelationshipGraphSnapshot,
  RELATIONSHIP_GRAPH_SNAPSHOT_VERSION,
  syncRelationshipGraphAdapter,
  type LoadedRelationshipGraphSnapshot,
  type RelationshipGraphAdapter,
  type RelationshipGraphAdapterContext,
  type RelationshipGraphAdapterReplaceContext,
  type RelationshipGraphAdapterSyncResult,
  type RelationshipGraphSnapshot,
} from "./adapter.js";
export {
  assertMemoryRelationshipGraphAdapterConformance,
  assertRelationshipGraphAdapterConformance,
  createRelationshipGraphScaleFixture,
  type RelationshipGraphAdapterConformanceCase,
  type RelationshipGraphAdapterConformanceReport,
  type RelationshipGraphScaleFixture,
  type RelationshipGraphScaleFixtureOptions,
  type RelationshipGraphScaleTopology,
} from "./conformance.js";
export {
  analyzeRelationshipSchedule,
  type GraphScheduleOptions,
  type RelationshipScheduleAnalysis,
  type RelationshipScheduleRow,
} from "./scheduling.js";
export {
  assembleWorkspaceRelationshipGraph,
  collectDanglingDependencyReferences,
  collectDuplicateDependencyRows,
  collectMissingDependencyTargetIds,
  normalizeDependencyGraphTarget,
  resolveWorkspaceRelationshipKindRegistry,
  type DanglingDependencyReference,
  type DanglingDependencyReferenceSummary,
  type DependencyReferenceHolder,
  type DependencyReferenceSource,
  type DuplicateDependencyRow,
  type WorkspaceRelationshipAssembly,
  type WorkspaceRelationshipItem,
  type WorkspaceRelationshipNodeDetails,
} from "./assembly.js";
export {
  auditWorkspaceRelationshipGraph,
  collectDuplicateRelationshipEdgeGroups,
  collectOrderingCycles,
  diffRelationshipAuditSnapshots,
  formatDuplicateEdgeGroup,
  type DuplicateRelationshipEdgeGroup,
  type RelationshipAuditDelta,
  type RelationshipAuditFinding,
  type RelationshipAuditFindingCode,
  type RelationshipAuditOptions,
  type RelationshipAuditReport,
  type RelationshipAuditSeverity,
  type RelationshipAuditSnapshot,
  type RelationshipCoverageProfile,
  type RelationshipCoverageTypeProfile,
} from "./governance.js";
export {
  clearDurableGraphCache,
  durableGraphCachePath,
  durableGraphCacheStatus,
  GRAPH_DURABLE_CACHE_MIN_ITEMS,
  GRAPH_DURABLE_CACHE_VERSION,
  graphAuditBaselinePath,
  loadGraphAuditBaseline,
  openDurableGraphCache,
  persistDurableGraphResult,
  saveGraphAuditBaseline,
  shouldPersistDurableGraphCache,
  type DurableGraphCacheEnvelope,
  type DurableGraphCacheStatus,
  type DurableGraphCacheView,
} from "./durable-cache.js";
export {
  enumerateRelationshipPaths,
  hierarchyAncestors,
  hierarchyDescendants,
  orderingPredecessors,
  orderingSuccessors,
  type GraphPathOptions,
  type GraphTraversalOptions,
  type RelationshipPath,
} from "./traversal.js";
export {
  computeWorkspaceGraphFingerprint,
  resetWorkspaceGraphCache,
  workspaceGraphCache,
  WorkspaceGraphCache,
  type GraphCacheMetadata,
  type WorkspaceGraphCacheLookup,
} from "./cache.js";
export {
  planRelationshipRemediation,
  type RelationshipRemediationCode,
  type RelationshipRemediationConfidence,
  type RelationshipRemediationOperation,
  type RelationshipRemediationPlan,
  type RelationshipRemediationPlanOptions,
  type RelationshipRemediationStep,
} from "./remediation.js";
export { collectNewOrderingCycleWarnings } from "./mutation-advisory.js";
export {
  GRAPH_SUBCOMMAND_VALUES,
  parseGraphSubcommand,
  runGraph,
  type GraphAnalyzeResult,
  type GraphArticulationResult,
  type GraphAuditResult,
  type GraphBridgeRow,
  type GraphCentralityResult,
  type GraphCentralityRow,
  type GraphCommandOptions,
  type GraphCommunitiesResult,
  type GraphCommunityRow,
  type GraphDominatorRow,
  type GraphDominatorsResult,
  type GraphExecutionSummary,
  type GraphImpactResult,
  type GraphImpactRow,
  type GraphIndexResult,
  type GraphKnowledgeSummary,
  type GraphPathRow,
  type GraphPathsResult,
  type GraphPlanResult,
  type GraphQueryCost,
  type GraphRedundancyResult,
  type GraphRedundancyRow,
  type GraphResult,
  type GraphScheduleRow,
  type GraphSlackResult,
  type GraphSubcommand,
  type GraphTraversalResult,
} from "./run.js";
