/**
 * @module sdk/authoring
 *
 * Provides the focused extension and package authoring surface.
 */
export * from "./compose.js";
export * from "./define.js";
export * from "./extension-contracts.js";
export { RESERVED_ITEM_FIELD_NAMES } from "../core/extensions/item-fields.js";
export {
  PM_PACKAGE_CONVENTIONAL_RESOURCE_ROOTS,
  PM_PACKAGE_RESOURCE_KINDS,
  collectPackageExtensionDirectories,
  readPmPackageManifest,
  type PmPackageCatalogLinkMap,
  type PmPackageCatalogMediaMap,
  type PmPackageCatalogMetadata,
  type PmPackageManifest,
  type PmPackageResourceKind,
  type PmPackageResourceMap,
} from "../core/packages/manifest.js";
export {
  BUILTIN_PROFILES,
  listProfiles,
  normalizeProfileName,
  PROFILE_NAMES,
  resolveProfile,
  type ProfileConfigEntry,
  type ProfileName,
  type ProfilePackageRecommendation,
  type ProfileTemplateEntry,
  type ProfileTemplateOptions,
  type ProjectProfileDefinition,
  type ProjectProfileRegistrationInput,
} from "../core/profile/profile-presets.js";
export {
  describeProfileComposition,
  describeProjectProfile,
  type ProjectProfileComposition,
  type ProjectProfileDescription,
  type ProjectProfilePackageSummary,
} from "../core/profile/profile-describe.js";
export {
  lintProjectProfile,
  PROFILE_LINT_CODES,
  PROFILE_LINT_DIMENSIONS,
  type ProfileLintCode,
  type ProfileLintDimension,
  type ProfileLintSeverity,
  type ProjectProfileLintFinding,
  type ProjectProfileLintReport,
} from "../core/profile/profile-lint.js";
export {
  planProfileApplication,
  type ProfileApplicationPlan,
  type ProfileChangeStatus,
  type ProfileComponentChange,
  type ProfileConfigChange,
  type ProfileConfigPlan,
  type ProfileCurrentState,
  type ProfilePackagePlan,
  type ProfileSchemaPlan,
  type ProfileTemplateChange,
  type ProfileTemplatePlan,
  type ProfileWorkflowChange,
  type ProfileWorkflowPlan,
} from "../core/profile/profile-plan.js";
export {
  EXTENSION_CAPABILITY_REGISTRATION_SURFACES,
  collectUsedExtensionCapabilities,
  reconcileExtensionCapabilityUsage,
  type CollectUsedExtensionCapabilitiesOptions,
  type ExtensionCapabilityUsageReconciliation,
} from "../core/extensions/capability-usage.js";
export {
  renderExtensionSurfaceMarkdown,
  type ExtensionSurfaceMarkdownOptions,
} from "../core/extensions/activation-summary-markdown.js";
export {
  createExtensionContributionInventory,
  normalizeExtensionContributionInventory,
} from "../core/extensions/contribution-inventory.js";
export type {
  AfterCommandAffectedItem,
  AfterCommandHook,
  AfterCommandHookContext,
  BeforeCommandHook,
  BeforeCommandHookContext,
  BeforeMutationHook,
  BeforeMutationHookContext,
  BeforeMutationHookDecision,
  CommandDefinition,
  ExtensionCommandArgumentDefinition,
  CommandHandler,
  CommandHandlerContext,
  CommandHandlerResult,
  ExtensionCommandSdk,
  CommandOverride,
  CommandOverrideContext,
  ExtensionServiceName,
  Exporter,
  ExporterRegistrationOptions,
  ExtensionActivationResult,
  ExtensionApi,
  ExtensionCommandRegistry,
  ExtensionDeactivationFailure,
  ExtensionDeactivationOptions,
  ExtensionDeactivationResult,
  ExtensionDiagnostic,
  ExtensionContributionInventory,
  ExtensionDiscoveryResult,
  ExtensionHookRegistry,
  ExtensionSelfIdentity,
  ExtensionLoadResult,
  ExtensionManifest,
  ExtensionManifestEngines,
  ExtensionMutationGuardSdk,
  ExtensionGovernancePolicy,
  ExtensionPolicyOverride,
  ExtensionProvenanceMetadata,
  ExtensionRuntimePermissionDeclaration,
  ExtensionSearchMode,
  ExtensionParserRegistry,
  ExtensionPreflightRegistry,
  ExtensionRegistrationRegistry,
  ExtensionRendererRegistry,
  ExtensionServiceRegistry,
  FlagValueType,
  FlagDefinition,
  ImportExportContext,
  ImportExportRegistrationOptions,
  Importer,
  OnIndexHook,
  OnIndexHookContext,
  OnReadHook,
  OnReadHookContext,
  OnWriteHook,
  OnWriteHookContext,
  OutputRendererFormat,
  ParserOverride,
  ParserOverrideContext,
  ParserOverrideDelta,
  PreflightOverride,
  PreflightOverrideContext,
  PreflightOverrideDelta,
  PreflightRuntimeDecision,
  RegisteredExtensionExporter,
  RegisteredExporterArtifactOutputContract,
  RegisteredExtensionFlagDefinitions,
  RegisteredExtensionHook,
  RegisteredExtensionImporter,
  RegisteredExtensionProjectProfile,
  RegisteredExtensionSchemaMigrationDefinition,
  RegisteredExtensionSearchProvider,
  RegisteredExtensionServiceOverride,
  RegisteredExtensionVectorStoreAdapter,
  RendererOverride,
  RendererOverrideContext,
  SchemaFieldDefinition,
  SchemaItemTypeCommandOptionPolicyDefinition,
  SchemaItemTypeOptionDefinition,
  SchemaItemTypeDefinition,
  SchemaMigrationDefinition,
  SchemaMigrationRunContext,
  SchemaMigrationRunner,
  SearchProviderEmbedBatchContext,
  SearchProviderEmbedContext,
  SearchProviderDefinition,
  SearchProviderHit,
  SearchProviderQueryContext,
  SearchProviderQueryResult,
  ServiceOverride,
  ServiceOverrideContext,
  ServiceOverrideDecision,
  VectorStoreAdapterDefinition,
  VectorStoreDeleteContext,
  VectorStoreQueryContext,
  VectorStoreQueryHit,
  VectorStoreUpsertContext,
  VectorStoreUpsertPoint,
} from "../core/extensions/loader.js";
