export interface CommanderOptionAliasContract {
  target: string;
  keys: string[];
}

export interface CliFlagContract {
  flag: string;
  short?: string;
}

export interface PiOptionFlagContract {
  param: string;
  flag: string;
  allowEmpty?: boolean;
  repeatable?: boolean;
  repeatableOrNone?: boolean;
  booleanish?: boolean;
}

export const PM_EXTENSION_CAPABILITY_CONTRACTS = [
  "commands",
  "renderers",
  "hooks",
  "schema",
  "importers",
  "search",
  "parser",
  "preflight",
  "services",
] as const;

export type PmExtensionCapabilityContract = (typeof PM_EXTENSION_CAPABILITY_CONTRACTS)[number];

export const PM_EXTENSION_SERVICE_NAME_CONTRACTS = [
  "output_format",
  "error_format",
  "help_format",
  "lock_acquire",
  "lock_release",
  "history_append",
  "item_store_write",
  "item_store_delete",
] as const;

export type PmExtensionServiceNameContract = (typeof PM_EXTENSION_SERVICE_NAME_CONTRACTS)[number];

function normalizeUniqueStringList(values: Iterable<string>): string[] {
  return [...new Set(Array.from(values).filter((value) => value.trim().length > 0))];
}

export const PM_CORE_COMMAND_NAMES = [
  "init",
  "config",
  "install",
  "create",
  "list",
  "list-all",
  "list-draft",
  "list-open",
  "list-in-progress",
  "list-blocked",
  "list-closed",
  "list-canceled",
  "calendar",
  "cal",
  "context",
  "ctx",
  "get",
  "search",
  "reindex",
  "history",
  "activity",
  "restore",
  "update",
  "close",
  "delete",
  "append",
  "comments",
  "notes",
  "learnings",
  "files",
  "docs",
  "test",
  "test-all",
  "stats",
  "health",
  "gc",
  "claim",
  "release",
  "beads",
  "todos",
  "completion",
  "help",
] as const;

export const PM_TOOL_ACTIONS = [
  "init",
  "config",
  "create",
  "list",
  "list-all",
  "list-draft",
  "list-open",
  "list-in-progress",
  "list-blocked",
  "list-closed",
  "list-canceled",
  "calendar",
  "context",
  "get",
  "search",
  "reindex",
  "history",
  "activity",
  "restore",
  "update",
  "close",
  "delete",
  "append",
  "comments",
  "notes",
  "learnings",
  "files",
  "docs",
  "test",
  "test-all",
  "stats",
  "health",
  "gc",
  "completion",
  "claim",
  "release",
  "beads-import",
  "todos-import",
  "todos-export",
  "start-task",
  "pause-task",
  "close-task",
] as const;

export type PmToolAction = (typeof PM_TOOL_ACTIONS)[number];

export const PI_LIST_FILTER_OPTION_CONTRACTS: PiOptionFlagContract[] = [
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "deadlineBefore", flag: "--deadline-before" },
  { param: "deadlineAfter", flag: "--deadline-after" },
  { param: "assignee", flag: "--assignee" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
  { param: "limit", flag: "--limit" },
];

export const PI_SEARCH_FILTER_OPTION_CONTRACTS: PiOptionFlagContract[] = [
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "deadlineBefore", flag: "--deadline-before" },
  { param: "deadlineAfter", flag: "--deadline-after" },
  { param: "limit", flag: "--limit" },
];

export const PI_SHARED_CREATE_UPDATE_OPTION_CONTRACTS: PiOptionFlagContract[] = [
  { param: "parent", flag: "--parent" },
  { param: "reviewer", flag: "--reviewer" },
  { param: "risk", flag: "--risk" },
  { param: "confidence", flag: "--confidence" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
  { param: "blockedBy", flag: "--blocked-by" },
  { param: "blockedReason", flag: "--blocked-reason" },
  { param: "unblockNote", flag: "--unblock-note" },
  { param: "reporter", flag: "--reporter" },
  { param: "severity", flag: "--severity" },
  { param: "environment", flag: "--environment" },
  { param: "reproSteps", flag: "--repro-steps" },
  { param: "resolution", flag: "--resolution" },
  { param: "expectedResult", flag: "--expected-result" },
  { param: "actualResult", flag: "--actual-result" },
  { param: "affectedVersion", flag: "--affected-version" },
  { param: "fixedVersion", flag: "--fixed-version" },
  { param: "component", flag: "--component" },
  { param: "regression", flag: "--regression", booleanish: true },
  { param: "customerImpact", flag: "--customer-impact" },
  { param: "definitionOfReady", flag: "--definition-of-ready", allowEmpty: true },
  { param: "order", flag: "--order" },
  { param: "goal", flag: "--goal" },
  { param: "objective", flag: "--objective" },
  { param: "value", flag: "--value" },
  { param: "impact", flag: "--impact" },
  { param: "outcome", flag: "--outcome" },
  { param: "whyNow", flag: "--why-now" },
];

export const PI_CREATE_OPTION_CONTRACTS: PiOptionFlagContract[] = [
  { param: "title", flag: "--title" },
  { param: "description", flag: "--description", allowEmpty: true },
  { param: "type", flag: "--type" },
  { param: "status", flag: "--status" },
  { param: "priority", flag: "--priority" },
  { param: "tags", flag: "--tags", allowEmpty: true },
  { param: "body", flag: "--body", allowEmpty: true },
  { param: "deadline", flag: "--deadline" },
  { param: "estimate", flag: "--estimate" },
  { param: "acceptanceCriteria", flag: "--acceptance-criteria", allowEmpty: true },
  { param: "author", flag: "--author" },
  { param: "message", flag: "--message", allowEmpty: true },
  { param: "reminder", flag: "--reminder", repeatable: true },
  { param: "event", flag: "--event", repeatable: true },
  { param: "typeOption", flag: "--type-option", repeatable: true },
  { param: "dep", flag: "--dep", repeatableOrNone: true },
  { param: "comment", flag: "--comment", repeatableOrNone: true },
  { param: "note", flag: "--note", repeatableOrNone: true },
  { param: "learning", flag: "--learning", repeatableOrNone: true },
  { param: "linkedFile", flag: "--file", repeatableOrNone: true },
  { param: "linkedTest", flag: "--test", repeatableOrNone: true },
  { param: "doc", flag: "--doc", repeatableOrNone: true },
];

export const PI_UPDATE_OPTION_CONTRACTS: PiOptionFlagContract[] = [
  { param: "title", flag: "--title" },
  { param: "description", flag: "--description", allowEmpty: true },
  { param: "status", flag: "--status" },
  { param: "priority", flag: "--priority" },
  { param: "type", flag: "--type" },
  { param: "tags", flag: "--tags", allowEmpty: true },
  { param: "deadline", flag: "--deadline" },
  { param: "estimate", flag: "--estimate" },
  { param: "acceptanceCriteria", flag: "--acceptance-criteria", allowEmpty: true },
  { param: "author", flag: "--author" },
  { param: "message", flag: "--message", allowEmpty: true },
  { param: "assignee", flag: "--assignee" },
  { param: "reminder", flag: "--reminder", repeatable: true },
  { param: "event", flag: "--event", repeatable: true },
  { param: "typeOption", flag: "--type-option", repeatable: true },
];

export const PI_CALENDAR_OPTION_CONTRACTS: PiOptionFlagContract[] = [
  { param: "view", flag: "--view" },
  { param: "date", flag: "--date" },
  { param: "from", flag: "--from" },
  { param: "to", flag: "--to" },
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "status", flag: "--status" },
  { param: "assignee", flag: "--assignee" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
  { param: "include", flag: "--include" },
  { param: "recurrenceLookaheadDays", flag: "--recurrence-lookahead-days" },
  { param: "recurrenceLookbackDays", flag: "--recurrence-lookback-days" },
  { param: "occurrenceLimit", flag: "--occurrence-limit" },
  { param: "limit", flag: "--limit" },
  { param: "format", flag: "--format" },
];

export const PI_CONTEXT_OPTION_CONTRACTS: PiOptionFlagContract[] = [
  { param: "date", flag: "--date" },
  { param: "from", flag: "--from" },
  { param: "to", flag: "--to" },
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "assignee", flag: "--assignee" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
  { param: "limit", flag: "--limit" },
  { param: "format", flag: "--format" },
];

export const SUBCOMMAND_GLOBAL_FLAG_CONTRACTS: CliFlagContract[] = [
  { flag: "--json" },
  { flag: "--quiet" },
  { flag: "--path" },
  { flag: "--no-extensions" },
  { flag: "--profile" },
  { flag: "--help" },
];

export const GLOBAL_FLAG_CONTRACTS: CliFlagContract[] = [
  ...SUBCOMMAND_GLOBAL_FLAG_CONTRACTS,
  { flag: "--version" },
];

export const LIST_FILTER_FLAG_CONTRACTS: CliFlagContract[] = [
  { flag: "--type" },
  { flag: "--tag" },
  { flag: "--priority" },
  { flag: "--deadline-before" },
  { flag: "--deadline-after" },
  { flag: "--assignee" },
  { flag: "--sprint" },
  { flag: "--release" },
  { flag: "--limit" },
  { flag: "--include-body" },
];

export const CREATE_FLAG_CONTRACTS: CliFlagContract[] = [
  { short: "-t", flag: "--title" },
  { short: "-d", flag: "--description" },
  { flag: "--type" },
  { short: "-s", flag: "--status" },
  { short: "-p", flag: "--priority" },
  { flag: "--tags" },
  { short: "-b", flag: "--body" },
  { flag: "--deadline" },
  { flag: "--estimate" },
  { flag: "--estimated-minutes" },
  { flag: "--acceptance-criteria" },
  { flag: "--ac" },
  { flag: "--author" },
  { flag: "--message" },
  { flag: "--assignee" },
  { flag: "--parent" },
  { flag: "--reviewer" },
  { flag: "--risk" },
  { flag: "--confidence" },
  { flag: "--sprint" },
  { flag: "--release" },
  { flag: "--blocked-by" },
  { flag: "--blocked-reason" },
  { flag: "--unblock-note" },
  { flag: "--reporter" },
  { flag: "--severity" },
  { flag: "--environment" },
  { flag: "--repro-steps" },
  { flag: "--resolution" },
  { flag: "--expected-result" },
  { flag: "--actual-result" },
  { flag: "--affected-version" },
  { flag: "--fixed-version" },
  { flag: "--component" },
  { flag: "--regression" },
  { flag: "--customer-impact" },
  { flag: "--definition-of-ready" },
  { flag: "--order" },
  { flag: "--rank" },
  { flag: "--goal" },
  { flag: "--objective" },
  { flag: "--value" },
  { flag: "--impact" },
  { flag: "--outcome" },
  { flag: "--why-now" },
  { flag: "--dep" },
  { flag: "--type-option" },
  { flag: "--type_option" },
  { flag: "--reminder" },
  { flag: "--event" },
  { flag: "--comment" },
  { flag: "--note" },
  { flag: "--learning" },
  { flag: "--file" },
  { flag: "--test" },
  { flag: "--doc" },
];

export const UPDATE_FLAG_CONTRACTS: CliFlagContract[] = [
  { short: "-t", flag: "--title" },
  { short: "-d", flag: "--description" },
  { short: "-s", flag: "--status" },
  { short: "-p", flag: "--priority" },
  { flag: "--type" },
  { flag: "--tags" },
  { flag: "--deadline" },
  { flag: "--estimate" },
  { flag: "--estimated-minutes" },
  { flag: "--acceptance-criteria" },
  { flag: "--ac" },
  { flag: "--assignee" },
  { flag: "--parent" },
  { flag: "--reviewer" },
  { flag: "--risk" },
  { flag: "--confidence" },
  { flag: "--sprint" },
  { flag: "--release" },
  { flag: "--blocked-by" },
  { flag: "--blocked-reason" },
  { flag: "--unblock-note" },
  { flag: "--reporter" },
  { flag: "--severity" },
  { flag: "--environment" },
  { flag: "--repro-steps" },
  { flag: "--resolution" },
  { flag: "--expected-result" },
  { flag: "--actual-result" },
  { flag: "--affected-version" },
  { flag: "--fixed-version" },
  { flag: "--component" },
  { flag: "--regression" },
  { flag: "--customer-impact" },
  { flag: "--definition-of-ready" },
  { flag: "--order" },
  { flag: "--rank" },
  { flag: "--goal" },
  { flag: "--objective" },
  { flag: "--value" },
  { flag: "--impact" },
  { flag: "--outcome" },
  { flag: "--why-now" },
  { flag: "--author" },
  { flag: "--message" },
  { flag: "--reminder" },
  { flag: "--event" },
  { flag: "--type-option" },
  { flag: "--type_option" },
  { flag: "--force" },
];

export const CALENDAR_FLAG_CONTRACTS: CliFlagContract[] = [
  { flag: "--view" },
  { flag: "--date" },
  { flag: "--from" },
  { flag: "--to" },
  { flag: "--past" },
  { flag: "--type" },
  { flag: "--tag" },
  { flag: "--priority" },
  { flag: "--status" },
  { flag: "--assignee" },
  { flag: "--sprint" },
  { flag: "--release" },
  { flag: "--include" },
  { flag: "--recurrence-lookahead-days" },
  { flag: "--recurrence-lookback-days" },
  { flag: "--occurrence-limit" },
  { flag: "--limit" },
  { flag: "--format" },
];

export const CONTEXT_FLAG_CONTRACTS: CliFlagContract[] = [
  { flag: "--date" },
  { flag: "--from" },
  { flag: "--to" },
  { flag: "--past" },
  { flag: "--type" },
  { flag: "--tag" },
  { flag: "--priority" },
  { flag: "--assignee" },
  { flag: "--sprint" },
  { flag: "--release" },
  { flag: "--limit" },
  { flag: "--format" },
];

export const SEARCH_FLAG_CONTRACTS: CliFlagContract[] = [
  { flag: "--mode" },
  { flag: "--include-linked" },
  { flag: "--limit" },
  { flag: "--type" },
  { flag: "--tag" },
  { flag: "--priority" },
  { flag: "--deadline-before" },
  { flag: "--deadline-after" },
];

export function toCompletionFlagString(flagContracts: CliFlagContract[], includeGlobal = true): string {
  const scoped = flagContracts.flatMap((entry) => [entry.short, entry.flag]).filter((value): value is string => Boolean(value));
  const all = includeGlobal
    ? [
        ...scoped,
        ...SUBCOMMAND_GLOBAL_FLAG_CONTRACTS.flatMap((entry) => [entry.short, entry.flag]).filter((value): value is string => Boolean(value)),
      ]
    : scoped;
  return normalizeUniqueStringList(all).join(" ");
}

export const CREATE_COMMANDER_STRING_OPTION_CONTRACTS: CommanderOptionAliasContract[] = [
  { target: "title", keys: ["title"] },
  { target: "description", keys: ["description"] },
  { target: "type", keys: ["type"] },
  { target: "status", keys: ["status"] },
  { target: "priority", keys: ["priority"] },
  { target: "tags", keys: ["tags"] },
  { target: "body", keys: ["body"] },
  { target: "deadline", keys: ["deadline"] },
  { target: "estimatedMinutes", keys: ["estimate", "estimatedMinutes", "estimated_minutes"] },
  { target: "acceptanceCriteria", keys: ["acceptanceCriteria", "acceptance_criteria", "ac"] },
  { target: "definitionOfReady", keys: ["definitionOfReady", "definition_of_ready"] },
  { target: "order", keys: ["order"] },
  { target: "rank", keys: ["rank"] },
  { target: "goal", keys: ["goal"] },
  { target: "objective", keys: ["objective"] },
  { target: "value", keys: ["value"] },
  { target: "impact", keys: ["impact"] },
  { target: "outcome", keys: ["outcome"] },
  { target: "whyNow", keys: ["whyNow", "why_now"] },
  { target: "author", keys: ["author"] },
  { target: "message", keys: ["message"] },
  { target: "assignee", keys: ["assignee"] },
  { target: "parent", keys: ["parent"] },
  { target: "reviewer", keys: ["reviewer"] },
  { target: "risk", keys: ["risk"] },
  { target: "confidence", keys: ["confidence"] },
  { target: "sprint", keys: ["sprint"] },
  { target: "release", keys: ["release"] },
  { target: "blockedBy", keys: ["blockedBy", "blocked_by"] },
  { target: "blockedReason", keys: ["blockedReason", "blocked_reason"] },
  { target: "unblockNote", keys: ["unblockNote", "unblock_note"] },
  { target: "reporter", keys: ["reporter"] },
  { target: "severity", keys: ["severity"] },
  { target: "environment", keys: ["environment"] },
  { target: "reproSteps", keys: ["reproSteps", "repro_steps"] },
  { target: "resolution", keys: ["resolution"] },
  { target: "expectedResult", keys: ["expectedResult", "expected_result"] },
  { target: "actualResult", keys: ["actualResult", "actual_result"] },
  { target: "affectedVersion", keys: ["affectedVersion", "affected_version"] },
  { target: "fixedVersion", keys: ["fixedVersion", "fixed_version"] },
  { target: "component", keys: ["component"] },
  { target: "regression", keys: ["regression"] },
  { target: "customerImpact", keys: ["customerImpact", "customer_impact"] },
];

export const CREATE_COMMANDER_REPEATABLE_OPTION_CONTRACTS: CommanderOptionAliasContract[] = [
  { target: "dep", keys: ["dep"] },
  { target: "comment", keys: ["comment"] },
  { target: "note", keys: ["note"] },
  { target: "learning", keys: ["learning"] },
  { target: "file", keys: ["file"] },
  { target: "test", keys: ["test"] },
  { target: "doc", keys: ["doc"] },
  { target: "reminder", keys: ["reminder"] },
  { target: "event", keys: ["event"] },
  { target: "typeOption", keys: ["typeOption", "type_option"] },
];

export const UPDATE_COMMANDER_STRING_OPTION_CONTRACTS: CommanderOptionAliasContract[] = [
  { target: "title", keys: ["title"] },
  { target: "description", keys: ["description"] },
  { target: "status", keys: ["status"] },
  { target: "priority", keys: ["priority"] },
  { target: "type", keys: ["type"] },
  { target: "tags", keys: ["tags"] },
  { target: "deadline", keys: ["deadline"] },
  { target: "estimatedMinutes", keys: ["estimate", "estimatedMinutes", "estimated_minutes"] },
  { target: "acceptanceCriteria", keys: ["acceptanceCriteria", "acceptance_criteria", "ac"] },
  { target: "definitionOfReady", keys: ["definitionOfReady", "definition_of_ready"] },
  { target: "order", keys: ["order"] },
  { target: "rank", keys: ["rank"] },
  { target: "goal", keys: ["goal"] },
  { target: "objective", keys: ["objective"] },
  { target: "value", keys: ["value"] },
  { target: "impact", keys: ["impact"] },
  { target: "outcome", keys: ["outcome"] },
  { target: "whyNow", keys: ["whyNow", "why_now"] },
  { target: "author", keys: ["author"] },
  { target: "message", keys: ["message"] },
  { target: "assignee", keys: ["assignee"] },
  { target: "parent", keys: ["parent"] },
  { target: "reviewer", keys: ["reviewer"] },
  { target: "risk", keys: ["risk"] },
  { target: "confidence", keys: ["confidence"] },
  { target: "sprint", keys: ["sprint"] },
  { target: "release", keys: ["release"] },
  { target: "blockedBy", keys: ["blockedBy", "blocked_by"] },
  { target: "blockedReason", keys: ["blockedReason", "blocked_reason"] },
  { target: "unblockNote", keys: ["unblockNote", "unblock_note"] },
  { target: "reporter", keys: ["reporter"] },
  { target: "severity", keys: ["severity"] },
  { target: "environment", keys: ["environment"] },
  { target: "reproSteps", keys: ["reproSteps", "repro_steps"] },
  { target: "resolution", keys: ["resolution"] },
  { target: "expectedResult", keys: ["expectedResult", "expected_result"] },
  { target: "actualResult", keys: ["actualResult", "actual_result"] },
  { target: "affectedVersion", keys: ["affectedVersion", "affected_version"] },
  { target: "fixedVersion", keys: ["fixedVersion", "fixed_version"] },
  { target: "component", keys: ["component"] },
  { target: "regression", keys: ["regression"] },
  { target: "customerImpact", keys: ["customerImpact", "customer_impact"] },
];

export const UPDATE_COMMANDER_REPEATABLE_OPTION_CONTRACTS: CommanderOptionAliasContract[] = [
  { target: "reminder", keys: ["reminder"] },
  { target: "event", keys: ["event"] },
  { target: "typeOption", keys: ["typeOption", "type_option"] },
];

export const LIST_COMMANDER_STRING_OPTION_CONTRACTS: CommanderOptionAliasContract[] = [
  { target: "type", keys: ["type"] },
  { target: "tag", keys: ["tag"] },
  { target: "priority", keys: ["priority"] },
  { target: "deadlineBefore", keys: ["deadlineBefore"] },
  { target: "deadlineAfter", keys: ["deadlineAfter"] },
  { target: "assignee", keys: ["assignee"] },
  { target: "sprint", keys: ["sprint"] },
  { target: "release", keys: ["release"] },
  { target: "limit", keys: ["limit"] },
];

export const SEARCH_COMMANDER_STRING_OPTION_CONTRACTS: CommanderOptionAliasContract[] = [
  { target: "mode", keys: ["mode"] },
  { target: "type", keys: ["type"] },
  { target: "tag", keys: ["tag"] },
  { target: "priority", keys: ["priority"] },
  { target: "deadlineBefore", keys: ["deadlineBefore"] },
  { target: "deadlineAfter", keys: ["deadlineAfter"] },
  { target: "limit", keys: ["limit"] },
];

export const CALENDAR_COMMANDER_STRING_OPTION_CONTRACTS: CommanderOptionAliasContract[] = [
  { target: "view", keys: ["view"] },
  { target: "date", keys: ["date"] },
  { target: "from", keys: ["from"] },
  { target: "to", keys: ["to"] },
  { target: "limit", keys: ["limit"] },
  { target: "type", keys: ["type"] },
  { target: "tag", keys: ["tag"] },
  { target: "priority", keys: ["priority"] },
  { target: "status", keys: ["status"] },
  { target: "assignee", keys: ["assignee"] },
  { target: "sprint", keys: ["sprint"] },
  { target: "release", keys: ["release"] },
  { target: "include", keys: ["include"] },
  { target: "recurrenceLookaheadDays", keys: ["recurrenceLookaheadDays", "recurrence_lookahead_days"] },
  { target: "recurrenceLookbackDays", keys: ["recurrenceLookbackDays", "recurrence_lookback_days"] },
  { target: "occurrenceLimit", keys: ["occurrenceLimit", "occurrence_limit"] },
  { target: "format", keys: ["format"] },
];

export const CONTEXT_COMMANDER_STRING_OPTION_CONTRACTS: CommanderOptionAliasContract[] = [
  { target: "date", keys: ["date"] },
  { target: "from", keys: ["from"] },
  { target: "to", keys: ["to"] },
  { target: "type", keys: ["type"] },
  { target: "tag", keys: ["tag"] },
  { target: "priority", keys: ["priority"] },
  { target: "assignee", keys: ["assignee"] },
  { target: "sprint", keys: ["sprint"] },
  { target: "release", keys: ["release"] },
  { target: "limit", keys: ["limit"] },
  { target: "format", keys: ["format"] },
];

export function readFirstStringFromCommanderOptions(
  options: Record<string, unknown>,
  contract: CommanderOptionAliasContract,
): string | undefined {
  for (const key of contract.keys) {
    const candidate = options[key];
    if (typeof candidate === "string") {
      return candidate;
    }
  }
  return undefined;
}

export function readStringArrayFromCommanderOptions(
  options: Record<string, unknown>,
  contract: CommanderOptionAliasContract,
): string[] | undefined {
  for (const key of contract.keys) {
    const candidate = options[key];
    if (Array.isArray(candidate)) {
      return candidate as string[];
    }
  }
  return undefined;
}

export const PM_TOOL_PARAMETERS_SCHEMA: Record<string, unknown> = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  type: "object",
  additionalProperties: false,
  required: ["action"],
  properties: {
    action: { type: "string", enum: [...PM_TOOL_ACTIONS] },
    json: { type: "boolean", default: true },
    quiet: { type: "boolean" },
    profile: { type: "boolean" },
    noExtensions: { type: "boolean" },
    path: { type: "string" },
    pmExecutable: { type: "string" },
    timeoutMs: { type: "number" },
    id: { type: "string" },
    target: { type: "string" },
    query: { type: "string" },
    keywords: { type: "string" },
    prefix: { type: "string" },
    scope: { type: "string" },
    configAction: { type: "string" },
    key: { type: "string" },
    title: { type: "string" },
    description: { type: "string" },
    type: { type: "string" },
    status: { type: "string" },
    priority: { anyOf: [{ type: "string" }, { type: "number" }] },
    tags: { type: "string" },
    body: { type: "string" },
    deadline: { type: "string" },
    estimate: { anyOf: [{ type: "string" }, { type: "number" }] },
    acceptanceCriteria: { type: "string" },
    author: { type: "string" },
    message: { type: "string" },
    assignee: { type: "string" },
    parent: { type: "string" },
    reviewer: { type: "string" },
    risk: { type: "string" },
    confidence: { anyOf: [{ type: "string" }, { type: "number" }] },
    sprint: { type: "string" },
    release: { type: "string" },
    blockedBy: { type: "string" },
    blockedReason: { type: "string" },
    unblockNote: { type: "string" },
    reporter: { type: "string" },
    severity: { type: "string" },
    environment: { type: "string" },
    reproSteps: { type: "string" },
    resolution: { type: "string" },
    expectedResult: { type: "string" },
    actualResult: { type: "string" },
    affectedVersion: { type: "string" },
    fixedVersion: { type: "string" },
    component: { type: "string" },
    regression: { anyOf: [{ type: "boolean" }, { type: "string" }, { type: "number" }] },
    customerImpact: { type: "string" },
    definitionOfReady: { type: "string" },
    order: { anyOf: [{ type: "string" }, { type: "number" }] },
    goal: { type: "string" },
    objective: { type: "string" },
    value: { type: "string" },
    impact: { type: "string" },
    outcome: { type: "string" },
    whyNow: { type: "string" },
    mode: { type: "string" },
    view: { type: "string" },
    date: { type: "string" },
    from: { type: "string" },
    to: { type: "string" },
    past: { type: "boolean" },
    include: { type: "string" },
    recurrenceLookaheadDays: { anyOf: [{ type: "string" }, { type: "number" }] },
    recurrenceLookbackDays: { anyOf: [{ type: "string" }, { type: "number" }] },
    occurrenceLimit: { anyOf: [{ type: "string" }, { type: "number" }] },
    includeLinked: { type: "boolean" },
    tag: { type: "string" },
    deadlineBefore: { type: "string" },
    deadlineAfter: { type: "string" },
    limit: { anyOf: [{ type: "string" }, { type: "number" }] },
    timeout: { anyOf: [{ type: "string" }, { type: "number" }] },
    force: { type: "boolean" },
    run: { type: "boolean" },
    shell: { type: "string" },
    file: { type: "string" },
    folder: { type: "string" },
    text: { type: "string" },
    add: { type: "array", items: { type: "string" } },
    remove: { type: "array", items: { type: "string" } },
    dep: { type: "array", items: { type: "string" } },
    comment: { type: "array", items: { type: "string" } },
    note: { type: "array", items: { type: "string" } },
    learning: { type: "array", items: { type: "string" } },
    linkedFile: { type: "array", items: { type: "string" } },
    linkedTest: { type: "array", items: { type: "string" } },
    doc: { type: "array", items: { type: "string" } },
    reminder: { type: "array", items: { type: "string" } },
    event: { type: "array", items: { type: "string" } },
    typeOption: { type: "array", items: { type: "string" } },
    criterion: { type: "array", items: { type: "string" } },
    format: { type: "string" },
  },
};
