/**
 * @module sdk/cli-contracts
 *
 * Public barrel for the pm CLI/MCP contract surface. Re-exports the public
 * members of the focused sibling modules — Commander option contracts,
 * enum/guard contracts, MCP tool option contracts, per-command flag contracts,
 * and the tool-parameter JSON Schemas — so existing import sites (sdk/index.ts,
 * mcp/server.ts, commands/contracts.ts, completion.ts, …) keep importing
 * everything from "./cli-contracts.js" unchanged. (The raw tool-parameter
 * property/metadata tables stay internal to tool-schema and are not surfaced
 * here.)
 */
export type {
  CommanderOptionAliasContract,
  CommanderOptionRegistrationContract,
} from "./cli-contracts/commander-types.js";
export {
  EXECUTABLE_COMMAND_ALIASES,
  PM_COMMAND_ALIAS_CONTRACTS,
  renderPmCommandAliasMigrationHint,
  resolvePmCommandAlias,
  type PmCommandAliasContract,
  type PmCommandAliasLifecycle,
  type PmCommandAliasRegistration,
} from "./cli-contracts/command-aliases.js";
export {
  ACTIVITY_COMMANDER_STRING_OPTION_CONTRACTS,
  CALENDAR_COMMANDER_STRING_OPTION_CONTRACTS,
  CONTEXT_COMMANDER_STRING_OPTION_CONTRACTS,
  LIST_COMMANDER_STRING_OPTION_CONTRACTS,
  NEXT_COMMANDER_STRING_OPTION_CONTRACTS,
  SEARCH_COMMANDER_STRING_OPTION_CONTRACTS,
  readFirstValueFromCommanderOptions,
  readFirstStringFromCommanderOptions,
  readStringArrayFromCommanderOptions,
} from "./cli-contracts/commander-types.js";
export {
  CREATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS,
  CREATE_COMMANDER_REPEATABLE_OPTION_CONTRACTS,
  CREATE_COMMANDER_STRING_OPTION_CONTRACTS,
  UPDATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS,
  UPDATE_COMMANDER_REPEATABLE_OPTION_CONTRACTS,
  UPDATE_COMMANDER_STRING_OPTION_CONTRACTS,
} from "./cli-contracts/commander-mutation-options.js";
// PM_* enum/guard contracts and the bulk tool-parameter property/metadata data
// tables live in sibling modules and are re-exported here so existing import
// sites (sdk/index.ts, mcp/server.ts, commands/contracts.ts, completion.ts, …)
// keep importing everything from "./cli-contracts.js" unchanged.
export {
  PM_EXTENSION_CAPABILITY_CONTRACTS,
  PM_EXTENSION_SERVICE_NAME_CONTRACTS,
  PM_EXTENSION_POLICY_MODE_CONTRACTS,
  PM_EXTENSION_TRUST_MODE_CONTRACTS,
  PM_EXTENSION_SANDBOX_PROFILE_CONTRACTS,
  PM_EXTENSION_POLICY_SURFACE_CONTRACTS,
  PM_CORE_COMMAND_NAMES,
  PM_CLI_ONLY_TOOL_ACTION_WAIVERS,
  PM_EXTENSION_PACKAGE_ACTION_SUBCOMMANDS,
  PM_DEPRECATED_TOOL_ACTIONS,
  PM_DISCOVERABLE_TOOL_ACTIONS,
  PM_TOOL_ACTIONS,
  analyzePmToolActionParity,
  isPmToolAction,
  isPmExtensionCapabilityContract,
  isPmExtensionServiceNameContract,
  isPmExtensionPolicyModeContract,
  isPmExtensionPolicySurfaceContract,
} from "./cli-contracts/enum-contracts.js";
export type {
  PmExtensionCapabilityContract,
  PmExtensionServiceNameContract,
  PmExtensionPolicyModeContract,
  PmExtensionTrustModeContract,
  PmExtensionSandboxProfileContract,
  PmExtensionPolicySurfaceContract,
  PmToolAction,
} from "./cli-contracts/enum-contracts.js";
export {
  TOOL_LIST_FILTER_OPTION_CONTRACTS,
  TOOL_AGGREGATE_OPTION_CONTRACTS,
  TOOL_SEARCH_FILTER_OPTION_CONTRACTS,
  TOOL_SHARED_CREATE_UPDATE_OPTION_CONTRACTS,
  TOOL_CREATE_OPTION_CONTRACTS,
  TOOL_UPDATE_OPTION_CONTRACTS,
  TOOL_UPDATE_MANY_FILTER_OPTION_CONTRACTS,
  TOOL_CLOSE_MANY_FILTER_OPTION_CONTRACTS,
  TOOL_CALENDAR_OPTION_CONTRACTS,
  TOOL_ACTIVITY_OPTION_CONTRACTS,
  TOOL_CONTEXT_OPTION_CONTRACTS,
  TOOL_DEPS_OPTION_CONTRACTS,
  TOOL_GRAPH_OPTION_CONTRACTS,
  TOOL_BULK_MUTATION_FILTER_OPTION_CONTRACT_SOURCE,
  TOOL_CREATE_OPTION_CONTRACT_SOURCE,
  TOOL_SHARED_CREATE_UPDATE_OPTION_CONTRACT_SOURCE,
  TOOL_UPDATE_OPTION_CONTRACT_SOURCE,
  verifyToolOptionCliParity,
  type ToolOptionCliParityFinding,
  type ToolOptionCliParityReport,
} from "./cli-contracts/tool-option-contracts.js";
export type {
  OptionsFromContracts,
  PmBulkMutationControlOptions,
  PmBulkMutationFilterOptions,
  PmCloseActionOptions,
  PmCloseManyActionOptions,
  PmCreateActionOptions,
  PmMutationAttributionOptions,
  PmOptionScalar,
  PmUpdateActionOptions,
  PmUpdateManyActionOptions,
} from "./cli-contracts/typed-action-inputs.js";
export type {
  CliFlagContract,
  ToolOptionFlagContract,
} from "./cli-contracts/flag-contracts.js";
export {
  withFlagAliasMetadata,
  compactFlagAliasContracts,
  resolvePmPositionalActionFlagContracts,
  SUBCOMMAND_GLOBAL_FLAG_CONTRACTS,
  GLOBAL_FLAG_CONTRACTS,
  LIST_FILTER_FLAG_CONTRACTS,
  AGGREGATE_FLAG_CONTRACTS,
  COMMENTS_FLAG_CONTRACTS,
  NOTES_FLAG_CONTRACTS,
  LEARNINGS_FLAG_CONTRACTS,
  FILES_FLAG_CONTRACTS,
  DOCS_FLAG_CONTRACTS,
  HISTORY_FLAG_CONTRACTS,
  HISTORY_REDACT_FLAG_CONTRACTS,
  HISTORY_REPAIR_FLAG_CONTRACTS,
  HISTORY_AUTHOR_ACKNOWLEDGE_FLAG_CONTRACTS,
  HISTORY_COMPACT_FLAG_CONTRACTS,
  MERGE_FLAG_CONTRACTS,
  SCHEMA_FLAG_CONTRACTS,
  PROFILE_FLAG_CONTRACTS,
  PLAN_FLAG_CONTRACTS,
  INIT_FLAG_CONTRACTS,
  CONFIG_FLAG_CONTRACTS,
  EXTENSION_FLAG_CONTRACTS,
  EXTENSION_SCOPE_FLAG_CONTRACTS,
  EXTENSION_INIT_FLAG_CONTRACTS,
  EXTENSION_MIGRATE_FLAG_CONTRACTS,
  PACKAGE_FLAG_CONTRACTS,
  PACKAGE_INIT_FLAG_CONTRACTS,
  EXTENSION_INSTALL_FLAG_CONTRACTS,
  EXTENSION_UNINSTALL_FLAG_CONTRACTS,
  EXTENSION_EXPLORE_FLAG_CONTRACTS,
  EXTENSION_DESCRIBE_FLAG_CONTRACTS,
  EXTENSION_ADOPT_ALL_FLAG_CONTRACTS,
  EXTENSION_ACTIVATE_FLAG_CONTRACTS,
  EXTENSION_DEACTIVATE_FLAG_CONTRACTS,
  EXTENSION_MANAGE_FLAG_CONTRACTS,
  EXTENSION_RELOAD_FLAG_CONTRACTS,
  EXTENSION_DOCTOR_FLAG_CONTRACTS,
  EXTENSION_CATALOG_FLAG_CONTRACTS,
  EXTENSION_ADOPT_FLAG_CONTRACTS,
  INSTALL_FLAG_CONTRACTS,
  UPGRADE_FLAG_CONTRACTS,
  REINDEX_FLAG_CONTRACTS,
  CLOSE_FLAG_CONTRACTS,
  CLOSE_MANY_FLAG_CONTRACTS,
  APPEND_FLAG_CONTRACTS,
  CLAIM_FLAG_CONTRACTS,
  RESTORE_FLAG_CONTRACTS,
  DELETE_FLAG_CONTRACTS,
  RELEASE_FLAG_CONTRACTS,
  START_TASK_FLAG_CONTRACTS,
  PAUSE_TASK_FLAG_CONTRACTS,
  CLOSE_TASK_FLAG_CONTRACTS,
  MEET_FLAG_CONTRACTS,
  EVENT_FLAG_CONTRACTS,
  EVENTS_FLAG_CONTRACTS,
  REMIND_FLAG_CONTRACTS,
  TEST_FLAG_CONTRACTS,
  TEST_ALL_FLAG_CONTRACTS,
  TELEMETRY_FLAG_CONTRACTS,
  TEST_RUNS_FLAG_CONTRACTS,
  GC_FLAG_CONTRACTS,
  STATS_FLAG_CONTRACTS,
  DUPLICATES_FLAG_CONTRACTS,
  HEALTH_FLAG_CONTRACTS,
  VALIDATE_FLAG_CONTRACTS,
  ASSURANCE_FLAG_CONTRACTS,
  CREATE_FLAG_CONTRACTS,
  ITEM_COMPLETE_FLAG_CONTRACTS,
  ITEM_MUTATE_FLAG_CONTRACTS,
  COPY_FLAG_CONTRACTS,
  FOCUS_FLAG_CONTRACTS,
  UPDATE_FLAG_CONTRACTS,
  UPDATE_MANY_FLAG_CONTRACTS,
  CALENDAR_FLAG_CONTRACTS,
  ACTIVITY_FLAG_CONTRACTS,
  CONTEXT_FLAG_CONTRACTS,
  GET_FLAG_CONTRACTS,
  GUIDE_FLAG_CONTRACTS,
  DEPS_FLAG_CONTRACTS,
  GRAPH_FLAG_CONTRACTS,
  EVAL_FLAG_CONTRACTS,
  WORKSPACE_FLAG_CONTRACTS,
  NEXT_FLAG_CONTRACTS,
  SEARCH_FLAG_CONTRACTS,
  CONTRACTS_FLAG_CONTRACTS,
  COMPLETION_FLAG_CONTRACTS,
  hasSubcommandFlagContractsForCommand,
  resolveSubcommandFlagContractsForCommand,
  toCompletionFlagString,
} from "./cli-contracts/flag-contracts.js";
export type { PmActionSchemaContract } from "./cli-contracts/tool-schema.js";
export {
  buildPmActionToolInputSchema,
  PM_TOOL_RESERVED_CUSTOM_FIELD_PROPERTIES,
  resolvePmToolCustomFieldCollision,
  CLOSE_ACTION_OPTION_KEYS,
  PLAN_CREATE_METADATA_PARAMETER_KEYS,
  PM_TOOL_ACTION_PARAMETER_CONTRACTS,
  PM_TOOL_PARAMETERS_SCHEMA_VERSION,
  PM_TOOL_PARAMETERS_SCHEMA_MAJOR,
  PM_PROVIDER_TOOL_PARAMETERS_SCHEMA_VERSION,
  PM_TOOL_PARAMETERS_SCHEMA,
  PM_PROVIDER_TOOL_PARAMETERS_SCHEMA,
  _testOnlyCliContracts,
} from "./cli-contracts/tool-schema.js";
export type {
  PmActionToolInputSchemaOptions,
  PmToolCustomFieldCollision,
} from "./cli-contracts/tool-schema.js";
export {
  analyzeSdkCliParameterCompleteness,
  type SdkCliActionParameterCoverage,
  type SdkCliCompletenessContractSource,
  type SdkCliParameterCoverageEntry,
  type SdkCliParameterDisposition,
} from "./cli-contracts/completeness.js";
export {
  PM_COMMAND_OUTPUT_BUDGET_CONTRACTS,
  PM_OUTPUT_BUDGET_CLASSES,
  PM_OUTPUT_DEGRADATION_STEPS,
  createPmCommandOutputBudget,
  definePmCommandOutputBudget,
  estimatePmOutputTokens,
  inferPmOutputBudgetClass,
  resolvePmCommandOutputBudget,
  type PmCommandOutputBudgetContract,
  type PmOutputBudgetClass,
  type PmOutputDegradationStep,
} from "./cli-contracts/agent-output-contracts.js";
