/**
 * @module sdk/core
 *
 * Provides the stable item lifecycle client and universal project data types.
 */
export {
  BASELINE_ITEM_FORMAT_VERSION,
  BUILTIN_ITEM_TYPE_VALUES,
  CONFIDENCE_TEXT_VALUES,
  CURRENT_ITEM_FORMAT_VERSION,
  DEPENDENCY_KIND_VALUES,
  EXIT_CODE,
  ISSUE_SEVERITY_VALUES,
  ITEM_TYPE_VALUES,
  PM_CLI_EXPECTED_ERROR_NAME,
  PmCliError,
  PmClient,
  RISK_VALUES,
  STATUS_VALUES,
  canonicalDocument,
  classifyItemFormatVersion,
  createPmCliExpectedError,
  effectiveItemFormatVersion,
  emptyImportedDocument,
  isPmCliExpectedError,
  normalizeItemFormatVersion,
  normalizeItemId,
  normalizeStatusInput,
  nowIso,
  runAction,
  serializeItemDocument,
  aggregate,
  append,
  claim,
  claimNext,
  close,
  comments,
  context,
  copy,
  create,
  deleteItem,
  deps,
  docs,
  files,
  filesDiscover,
  focus,
  get,
  graph,
  learnings,
  list,
  next,
  notes,
  release,
  restore,
  search,
  update,
  type AggregateOptions,
  type AggregateResult,
  type AggregateRow,
  type AppendCommandOptions,
  type AppendResult,
  type ClaimNextOptions,
  type ClaimResult,
  type CloseResult,
  type CommentsCommandOptions,
  type CommentsResult,
  type ContextOptions,
  type ContextResult,
  type CopyResult,
  type CreateResult,
  type Dependency,
  type DeleteResult,
  type DepsCommandOptions,
  type DepsResult,
  type DocsCommandOptions,
  type DocsResult,
  type FilesCommandOptions,
  type FilesDiscoverOptions,
  type FilesDiscoverResult,
  type FilesResult,
  type FocusResult,
  type GetOptions,
  type GetResult,
  type ItemFormatVersionScanEntry,
  type ItemFormatVersionScanResult,
  type ItemFormatVersionStatus,
  type LearningsCommandOptions,
  type LearningsResult,
  type ListOptions,
  type ListResult,
  type NextOptions,
  type NextResult,
  type NotesCommandOptions,
  type NotesResult,
  type PmActionInput,
  type PmActionName,
  type PmActionOptions,
  type PmClientOptions,
  type ReleaseResult,
  type RestoreResult,
  type SearchOptions,
  type SearchResult,
  type UpdateResult,
} from "./runtime.js";
export * from "./core-governance.js";
export * from "./agent-session-context.js";
export type {
  ItemDocument,
  ItemMetadata,
  ItemStatus,
  ItemType,
  PmSettings,
} from "../types/index.js";
