/**
 * @module sdk/generated-error-code-catalog
 *
 * Generated by scripts/generate-error-code-catalog.mjs. Do not edit manually.
 */
import { definePmErrorCodeCatalog } from "./error-code-catalog.js";

/** Exhaustive catalog generated from literal error guidance declarations. */
export const PM_ERROR_CODE_CATALOG = definePmErrorCodeCatalog([
  {
    code: "acceptance_criteria_semicolon_forbidden",
    meaning: "Acceptance criteria semicolon forbidden condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/item/parse.ts"],
  },
  {
    code: "already_claimed_by",
    meaning: "Already claimed by condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/claim.ts"],
  },
  {
    code: "ambiguous_list_all",
    meaning: "Ambiguous list all condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/register-list-query.ts"],
  },
  {
    code: "ambiguous_option_combination",
    meaning: "Ambiguous option combination condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/plan.ts"],
  },
  {
    code: "annotation_flag_like_value",
    meaning: "Annotation flag like value condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/annotations.ts"],
  },
  {
    code: "annotation_message_without_text",
    meaning: "Annotation message without text condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/annotations.ts"],
  },
  {
    code: "append_empty_body",
    meaning: "Append empty body condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/append.ts"],
  },
  {
    code: "body_file_conflicts_with_body",
    meaning: "Body file conflicts with body condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/io/body-file.ts"],
  },
  {
    code: "body_file_missing_path",
    meaning: "Body file missing path condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/io/body-file.ts"],
  },
  {
    code: "body_file_unreadable",
    meaning: "Body file unreadable condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/io/body-file.ts"],
  },
  {
    code: "bundle_integrity_torn_install",
    meaning: "Bundle integrity torn install condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/bundle-integrity.ts"],
  },
  {
    code: "capability_undeclared",
    meaning: "Capability undeclared condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/compose.ts"],
  },
  {
    code: "capability_unused",
    meaning: "Capability unused condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/compose.ts"],
  },
  {
    code: "child_projection_item_bound_exceeded",
    meaning: "Child projection item bound exceeded condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/item-children.ts"],
  },
  {
    code: "close_reason_required",
    meaning: "Close reason required condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/close-many.ts", "cli/commands/close.ts"],
  },
  {
    code: "close_through_update",
    meaning: "Close through update condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/telemetry/observability.ts"],
  },
  {
    code: "close_validation_missing_fields",
    meaning: "Close validation missing fields condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/close.ts"],
  },
  {
    code: "collected_zero_items",
    meaning: "Collected zero items condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/test/execution.ts"],
  },
  {
    code: "command_failed",
    meaning: "Command failed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts"],
  },
  {
    code: "command_namespace",
    meaning: "Command namespace condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/contracts.ts"],
  },
  {
    code: "command_override_conflict",
    meaning: "Command override conflict condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/compose.ts"],
  },
  {
    code: "config_duplicate",
    meaning: "Config duplicate condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "config_key_unknown",
    meaning: "Config key unknown condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "config_value_invalid",
    meaning: "Config value invalid condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "conflicting_lifecycle_owner",
    meaning: "Conflicting lifecycle owner condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/register-operations.ts"],
  },
  {
    code: "context_takes_no_item_argument",
    meaning: "Context takes no item argument condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts"],
  },
  {
    code: "create_positional_type_without_title",
    meaning: "Create positional type without title condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/register-mutation.ts"],
  },
  {
    code: "dependency_edge_not_allowed",
    meaning: "Dependency edge not allowed condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/dependency-flag-validation.ts"],
  },
  {
    code: "duplicate_command",
    meaning: "Duplicate command condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/compose.ts"],
  },
  {
    code: "duplicate_edge",
    meaning: "Duplicate edge condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/graph/remediation.ts"],
  },
  {
    code: "duplicate_sweep_cost_limit",
    meaning: "Duplicate sweep cost limit condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/similarity.ts"],
  },
  {
    code: "duplicate_target_circular",
    meaning: "Duplicate target circular condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/close.ts"],
  },
  {
    code: "duplicate_target_is_duplicate",
    meaning: "Duplicate target is duplicate condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/close.ts"],
  },
  {
    code: "duplicate_target_missing",
    meaning: "Duplicate target missing condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/close.ts"],
  },
  {
    code: "duplicate_target_self",
    meaning: "Duplicate target self condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/close.ts"],
  },
  {
    code: "empty_surface",
    meaning: "Empty surface condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/compose.ts"],
  },
  {
    code: "event_cursor_query_mismatch",
    meaning: "Event cursor query mismatch condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/mutation-events.ts"],
  },
  {
    code: "event_index_unavailable",
    meaning: "Event index unavailable condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/mutation-events.ts"],
  },
  {
    code: "extension_dependency_name_unsafe",
    meaning: "Extension dependency name unsafe condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension/install-sources.ts"],
  },
  {
    code: "extension_dependency_spec_invalid",
    meaning: "Extension dependency spec invalid condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension/install-sources.ts"],
  },
  {
    code: "extension_dependency_version_unsafe",
    meaning: "Extension dependency version unsafe condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension/install-sources.ts"],
  },
  {
    code: "extension_install_soft_failed",
    meaning: "Extension install soft failed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/register-setup.ts"],
  },
  {
    code: "extension_install_source_contains_destination",
    meaning: "Extension install source contains destination condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension/install-runtime.ts"],
  },
  {
    code: "extension_item_field_reserved",
    meaning: "Extension item field reserved condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/extensions/item-fields.ts"],
  },
  {
    code: "extension_item_field_type_conflict",
    meaning: "Extension item field type conflict condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/extensions/item-fields.ts"],
  },
  {
    code: "extension_item_field_unknown",
    meaning: "Extension item field unknown condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/extensions/item-fields.ts"],
  },
  {
    code: "extension_update_health_partial_coverage",
    meaning: "Extension update health partial coverage condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "field_duplicate",
    meaning: "Field duplicate condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "field_invalid",
    meaning: "Field invalid condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "github_source_entry_unbuilt",
    meaning: "Github source entry unbuilt condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension/shared.ts"],
  },
  {
    code: "history_drift_chain_mismatch",
    meaning: "History drift chain mismatch condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "history_drift_hash_mismatch",
    meaning: "History drift hash mismatch condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "history_drift_missing_stream",
    meaning: "History drift missing stream condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "history_drift_unreadable_stream",
    meaning: "History drift unreadable stream condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "history_merge_conflict_markers_detected",
    meaning: "History merge conflict markers detected condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/history/read.ts"],
  },
  {
    code: "history_stream_over_compact_threshold",
    meaning: "History stream over compact threshold condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "history_target_out_of_range",
    meaning: "History target out of range condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/history/projection.ts"],
  },
  {
    code: "history_unknown_author_events",
    meaning: "History unknown author events condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "init_existing_settings_requires_force",
    meaning: "Init existing settings requires force condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/init.ts"],
  },
  {
    code: "init_id_prefix_conflict",
    meaning: "Init id prefix conflict condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/init.ts"],
  },
  {
    code: "init_id_prefix_path_like",
    meaning: "Init id prefix path like condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/init.ts"],
  },
  {
    code: "integrity_history_conflict_marker",
    meaning: "Integrity history conflict marker condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "integrity_history_invalid_json",
    meaning: "Integrity history invalid json condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "integrity_history_unreadable",
    meaning: "Integrity history unreadable condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "integrity_item_ahead_format_version",
    meaning: "Integrity item ahead format version condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "integrity_item_conflict_marker",
    meaning: "Integrity item conflict marker condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "integrity_item_outdated_format_version",
    meaning: "Integrity item outdated format version condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "integrity_item_parse_failed",
    meaning: "Integrity item parse failed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "integrity_item_unreadable",
    meaning: "Integrity item unreadable condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "invalid_argument_value",
    meaning: "Invalid argument value condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: [
      "cli/commands/create.ts",
      "cli/error-guidance.ts",
      "core/telemetry/observability.ts",
    ],
  },
  {
    code: "invalid_command_usage",
    meaning: "Invalid command usage condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts", "core/telemetry/observability.ts"],
  },
  {
    code: "invalid_event_cursor",
    meaning: "Invalid event cursor condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/mutation-events.ts"],
  },
  {
    code: "invalid_event_follow_interval",
    meaning: "Invalid event follow interval condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/mutation-events.ts"],
  },
  {
    code: "invalid_event_limit",
    meaning: "Invalid event limit condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/mutation-events.ts"],
  },
  {
    code: "invalid_event_since",
    meaning: "Invalid event since condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/mutation-events.ts"],
  },
  {
    code: "invalid_query_cursor",
    meaning: "Invalid query cursor condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/pagination.ts"],
  },
  {
    code: "item_document_invalid",
    meaning: "Item document invalid condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/item/item-format.ts"],
  },
  {
    code: "item_document_roundtrip_failed",
    meaning: "Item document roundtrip failed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/item/item-format.ts"],
  },
  {
    code: "item_id_collision",
    meaning: "Item id collision condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/copy.ts"],
  },
  {
    code: "item_not_found",
    meaning: "Item not found condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts", "core/telemetry/observability.ts"],
  },
  {
    code: "likely_duplicate",
    meaning: "Likely duplicate condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/similarity.ts"],
  },
  {
    code: "linked_test_value_not_quoted",
    meaning: "Linked test value not quoted condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts"],
  },
  {
    code: "list_source_incomplete",
    meaning: "List source incomplete condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/query/list.ts"],
  },
  {
    code: "local_source_not_found_bare_name",
    meaning: "Local source not found bare name condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension/install-sources.ts"],
  },
  {
    code: "lock_conflict",
    meaning: "Lock conflict condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: [
      "cli/error-guidance.ts",
      "core/lock/lock.ts",
      "core/telemetry/observability.ts",
    ],
  },
  {
    code: "locks_stale_count",
    meaning: "Locks stale count condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "locks_unreadable",
    meaning: "Locks unreadable condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "malformed_plan_step_evidence",
    meaning: "Malformed plan step evidence condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/plan.ts"],
  },
  {
    code: "manifest_capabilities_absent",
    meaning: "Manifest capabilities absent condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/compose.ts"],
  },
  {
    code: "merge_conflict_markers_detected",
    meaning: "Merge conflict markers detected condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/item/item-format.ts"],
  },
  {
    code: "merge_git_config_unwritable",
    meaning: "Merge git config unwritable condition.",
    stability: "stable",
    exit_code: 5,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/merge/install.ts"],
  },
  {
    code: "merge_root_not_found",
    meaning: "Merge root not found condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/merge/install.ts"],
  },
  {
    code: "missing_directory",
    meaning: "Missing directory condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "missing_lifecycle_target",
    meaning: "Missing lifecycle target condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension.ts"],
  },
  {
    code: "missing_required_argument",
    meaning: "Missing required argument condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: [
      "cli/error-guidance.ts",
      "cli/main.ts",
      "cli/register-mutation.ts",
      "core/telemetry/observability.ts",
      "sdk/history-redact.ts",
      "sdk/invocation-author.ts",
    ],
  },
  {
    code: "missing_required_option",
    meaning: "Missing required option condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: [
      "cli/commands/create.ts",
      "cli/commands/plan.ts",
      "cli/error-guidance.ts",
      "core/telemetry/observability.ts",
    ],
  },
  {
    code: "module_import_failed",
    meaning: "Module import failed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts"],
  },
  {
    code: "multi_target_github_install_ambiguous",
    meaning: "Multi target github install ambiguous condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/register-setup.ts"],
  },
  {
    code: "mutation_author_required",
    meaning: "Mutation author required condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/mutation-guard.ts"],
  },
  {
    code: "mutation_secret_guard_blocked",
    meaning: "Mutation secret guard blocked condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/mutation-guard.ts"],
  },
  {
    code: "no_matching_tests",
    meaning: "No matching tests condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/test/execution.ts"],
  },
  {
    code: "no_projects_matched_filters",
    meaning: "No projects matched filters condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/test/execution.ts"],
  },
  {
    code: "no_test_files_found",
    meaning: "No test files found condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/test/execution.ts"],
  },
  {
    code: "no_tests_found",
    meaning: "No tests found condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/test/execution.ts"],
  },
  {
    code: "no_update_fields",
    meaning: "No update fields condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts", "core/telemetry/observability.ts"],
  },
  {
    code: "npm_package_not_found",
    meaning: "Npm package not found condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension/install-sources.ts"],
  },
  {
    code: "ownership_conflict",
    meaning: "Ownership conflict condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: [
      "cli/error-guidance.ts",
      "core/telemetry/observability.ts",
      "sdk/annotations.ts",
    ],
  },
  {
    code: "ownership_dependency_bypass_restricted_options",
    meaning: "Ownership dependency bypass restricted options condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/update.ts"],
  },
  {
    code: "ownership_metadata_bypass_restricted_options",
    meaning: "Ownership metadata bypass restricted options condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/update.ts"],
  },
  {
    code: "package_spec_empty",
    meaning: "Package spec empty condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "profile_name_empty",
    meaning: "Profile name empty condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "profile_name_not_normalized",
    meaning: "Profile name not normalized condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "profile_summary_empty",
    meaning: "Profile summary empty condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "profile_title_empty",
    meaning: "Profile title empty condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "redundant_edge",
    meaning: "Redundant edge condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/graph/remediation.ts"],
  },
  {
    code: "reindex_already_running",
    meaning: "Reindex already running condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/reindex.ts"],
  },
  {
    code: "reserved_item_field",
    meaning: "Reserved item field condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/compose.ts"],
  },
  {
    code: "schema_migration_input_required",
    meaning: "Schema migration input required condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/migration-gates.ts"],
  },
  {
    code: "settings_read_fs_error",
    meaning: "Settings read fs error condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "settings_read_invalid_json",
    meaning: "Settings read invalid json condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "settings_read_invalid_schema",
    meaning: "Settings read invalid schema condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "settings_read_merge_failed",
    meaning: "Settings read merge failed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "status_duplicate",
    meaning: "Status duplicate condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "status_invalid",
    meaning: "Status invalid condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "stdin_json_invalid",
    meaning: "Stdin json invalid condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/structured-mutations.ts"],
  },
  {
    code: "stdin_json_unknown_key",
    meaning: "Stdin json unknown key condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/structured-mutations.ts"],
  },
  {
    code: "telemetry_endpoint_probe_failed",
    meaning: "Telemetry endpoint probe failed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "telemetry_endpoint_probe_http_status",
    meaning: "Telemetry endpoint probe http status condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "telemetry_otel_export_failing",
    meaning: "Telemetry otel export failing condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "telemetry_queue_high_retries",
    meaning: "Telemetry queue high retries condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "telemetry_queue_invalid_rows",
    meaning: "Telemetry queue invalid rows condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "telemetry_queue_pending",
    meaning: "Telemetry queue pending condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "telemetry_schema_version_behind",
    meaning: "Telemetry schema version behind condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "telemetry_state_invalid_json",
    meaning: "Telemetry state invalid json condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "template_type_unknown",
    meaning: "Template type unknown condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "terminal_plan_mutation",
    meaning: "Terminal plan mutation condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/plan.ts"],
  },
  {
    code: "terminal_state_conflict",
    meaning: "Terminal state conflict condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/telemetry/observability.ts"],
  },
  {
    code: "tracked_runtime_cache_files",
    meaning: "Tracked runtime cache files condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "tracker_not_initialized",
    meaning: "Tracker not initialized condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts", "core/telemetry/observability.ts"],
  },
  {
    code: "tracker_root_missing",
    meaning: "Tracker root missing condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/store/item-store.ts"],
  },
  {
    code: "tracker_root_not_directory",
    meaning: "Tracker root not directory condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/store/item-store.ts"],
  },
  {
    code: "type_duplicate",
    meaning: "Type duplicate condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "type_invalid",
    meaning: "Type invalid condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "unknown_command",
    meaning: "Unknown command condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: [
      "cli/commands/contracts.ts",
      "cli/error-guidance.ts",
      "core/telemetry/observability.ts",
    ],
  },
  {
    code: "unknown_context_intent",
    meaning: "Unknown context intent condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/context-intent-contracts.ts"],
  },
  {
    code: "unknown_error",
    meaning: "Unknown error condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts"],
  },
  {
    code: "unknown_field",
    meaning: "Unknown field condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/schema.ts"],
  },
  {
    code: "unknown_field_projection",
    meaning: "Unknown field projection condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/get.ts", "sdk/query/list.ts"],
  },
  {
    code: "unknown_item_type",
    meaning: "Unknown item type condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/schema.ts"],
  },
  {
    code: "unknown_lifecycle_action",
    meaning: "Unknown lifecycle action condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/extension.ts"],
  },
  {
    code: "unknown_option",
    meaning: "Unknown option condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts", "core/telemetry/observability.ts"],
  },
  {
    code: "unknown_plan_template",
    meaning: "Unknown plan template condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/plan.ts"],
  },
  {
    code: "unknown_status",
    meaning: "Unknown status condition.",
    stability: "stable",
    exit_code: 3,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/schema.ts"],
  },
  {
    code: "unknown_subcommand",
    meaning: "Unknown subcommand condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: [
      "cli/register-mutation.ts",
      "cli/register-operations.ts",
      "sdk/telemetry.ts",
    ],
  },
  {
    code: "unsupported_update_option",
    meaning: "Unsupported update option condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/error-guidance.ts"],
  },
  {
    code: "validate_command_references_stale_pm_ids",
    meaning: "Validate command references stale pm ids condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_files_missing_linked_paths",
    meaning: "Validate files missing linked paths condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_files_orphaned_paths",
    meaning: "Validate files orphaned paths condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_files_tracked_all_strict_forces_pm_internals",
    meaning: "Validate files tracked all strict forces pm internals condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_format_version_ahead_items",
    meaning: "Validate format version ahead items condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_format_version_outdated_items",
    meaning: "Validate format version outdated items condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_hierarchy_parent_cycle",
    meaning: "Validate hierarchy parent cycle condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_hierarchy_parent_cycle_error",
    meaning: "Validate hierarchy parent cycle error condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_history_drift_chain_mismatches",
    meaning: "Validate history drift chain mismatches condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_history_drift_hash_mismatches",
    meaning: "Validate history drift hash mismatches condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_history_drift_missing_streams",
    meaning: "Validate history drift missing streams condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_history_drift_unreadable_streams",
    meaning: "Validate history drift unreadable streams condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_history_unknown_author_events",
    meaning: "Validate history unknown author events condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_lifecycle_active_closure_like_metadata",
    meaning: "Validate lifecycle active closure like metadata condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_lifecycle_active_terminal_parent",
    meaning: "Validate lifecycle active terminal parent condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_lifecycle_dependency_cycles",
    meaning: "Validate lifecycle dependency cycles condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_lifecycle_dependency_cycles_error",
    meaning: "Validate lifecycle dependency cycles error condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_lifecycle_stale_blockers",
    meaning: "Validate lifecycle stale blockers condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_merge_fence_drift",
    meaning: "Validate merge fence drift condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_custom_profile_missing_required_fields",
    meaning:
      "Validate metadata custom profile missing required fields condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_duplicate_issue_codes",
    meaning: "Validate metadata duplicate issue codes condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_missing_acceptance_criteria",
    meaning: "Validate metadata missing acceptance criteria condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_missing_close_reason",
    meaning: "Validate metadata missing close reason condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_missing_confidence",
    meaning: "Validate metadata missing confidence condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_missing_estimate",
    meaning: "Validate metadata missing estimate condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_missing_release",
    meaning: "Validate metadata missing release condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_missing_reviewer",
    meaning: "Validate metadata missing reviewer condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_missing_risk",
    meaning: "Validate metadata missing risk condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_metadata_missing_sprint",
    meaning: "Validate metadata missing sprint condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_resolution_missing_fields",
    meaning: "Validate resolution missing fields condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_storage_duplicate_item_ids",
    meaning: "Validate storage duplicate item ids condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_storage_history_conflict_markers",
    meaning: "Validate storage history conflict markers condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_storage_resurrected_items",
    meaning: "Validate storage resurrected items condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_storage_tracked_runtime_cache_files",
    meaning: "Validate storage tracked runtime cache files condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_storage_unparseable_config",
    meaning: "Validate storage unparseable config condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_storage_unparseable_history",
    meaning: "Validate storage unparseable history condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "validate_storage_unreadable_items",
    meaning: "Validate storage unreadable items condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "vectorization_embedding_identity_changed",
    meaning: "Vectorization embedding identity changed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "vectorization_stale_items_remaining",
    meaning: "Vectorization stale items remaining condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/diagnostics/remediation.ts"],
  },
  {
    code: "workflow_duplicate_type",
    meaning: "Workflow duplicate type condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "workflow_status_unknown",
    meaning: "Workflow status unknown condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "workflow_transition_malformed",
    meaning: "Workflow transition malformed condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "workflow_type_empty",
    meaning: "Workflow type empty condition.",
    stability: "stable",
    exit_code: 1,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "workflow_type_unknown",
    meaning: "Workflow type unknown condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/profile/profile-lint.ts"],
  },
  {
    code: "workspace_history_state_conflict",
    meaning: "Workspace history state conflict condition.",
    stability: "stable",
    exit_code: 4,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["core/history/workspace-history.ts"],
  },
  {
    code: "workspace_root_pm_path",
    meaning: "Workspace root pm path condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["sdk/init.ts"],
  },
  {
    code: "wrong_item_type",
    meaning: "Wrong item type condition.",
    stability: "stable",
    exit_code: 2,
    recovery:
      "Inspect the structured error guidance and retry the suggested command.",
    sources: ["cli/commands/plan.ts"],
  },
]);
