/**
 * @module sdk/generated-error-code-catalog
 *
 * Generated by scripts/generate-error-code-catalog.mjs. Do not edit manually.
 */
import { definePmErrorCodeCatalog } from "./error-code-catalog.js";
import { PM_ERROR_CODE_CATALOG_PART_1 } from "./generated/generated-error-code-catalog-part-1.js";
import { PM_ERROR_CODE_CATALOG_PART_2 } from "./generated/generated-error-code-catalog-part-2.js";

/** Exhaustive catalog generated from literal error guidance declarations. */
export const PM_ERROR_CODE_CATALOG = definePmErrorCodeCatalog([
  ...PM_ERROR_CODE_CATALOG_PART_1,
  ...PM_ERROR_CODE_CATALOG_PART_2,
]);
