/**
 * @module sdk/index
 *
 * Defines public SDK APIs and package-author helpers for Index.
 */
import {
  EXTENSION_CAPABILITY_CONTRACT,
  EXTENSION_CAPABILITY_CONTRACT_VERSION,
  EXTENSION_CAPABILITY_LEGACY_ALIASES,
  KNOWN_EXTENSION_CAPABILITIES,
  KNOWN_EXTENSION_POLICY_MODES,
  KNOWN_EXTENSION_POLICY_SURFACES,
  KNOWN_EXTENSION_SANDBOX_PROFILES,
  KNOWN_EXTENSION_TRUST_MODES,
} from "../core/extensions/loader.js";
export {
  PM_PACKAGE_CONVENTIONAL_RESOURCE_ROOTS,
  PM_PACKAGE_RESOURCE_KINDS,
  collectPackageExtensionDirectories,
  readPmPackageManifest,
  type PmPackageCatalogLinkMap,
  type PmPackageCatalogMediaMap,
  type PmPackageCatalogMetadata,
  type PmPackageManifest,
  type PmPackageResourceKind,
  type PmPackageResourceMap,
} from "../core/packages/manifest.js";
export type { CommanderOptionAliasContract, CommanderOptionRegistrationContract } from "./cli-contracts.js";
export {
  ACTIVITY_COMMANDER_STRING_OPTION_CONTRACTS,
  APPEND_FLAG_CONTRACTS,
  CALENDAR_COMMANDER_STRING_OPTION_CONTRACTS,
  CALENDAR_FLAG_CONTRACTS,
  CLAIM_FLAG_CONTRACTS,
  CLOSE_FLAG_CONTRACTS,
  CLOSE_MANY_FLAG_CONTRACTS,
  CLOSE_TASK_FLAG_CONTRACTS,
  COMMENTS_AUDIT_FLAG_CONTRACTS,
  COMMENTS_FLAG_CONTRACTS,
  COMPLETION_FLAG_CONTRACTS,
  CONFIG_FLAG_CONTRACTS,
  CONTEXT_COMMANDER_STRING_OPTION_CONTRACTS,
  CONTEXT_FLAG_CONTRACTS,
  CONTRACTS_FLAG_CONTRACTS,
  COPY_FLAG_CONTRACTS,
  CREATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS,
  CREATE_COMMANDER_REPEATABLE_OPTION_CONTRACTS,
  CREATE_COMMANDER_STRING_OPTION_CONTRACTS,
  CREATE_FLAG_CONTRACTS,
  DELETE_FLAG_CONTRACTS,
  DEDUPE_AUDIT_FLAG_CONTRACTS,
  DEDUPE_MERGE_FLAG_CONTRACTS,
  DEPS_FLAG_CONTRACTS,
  DOCS_FLAG_CONTRACTS,
  EVAL_FLAG_CONTRACTS,
  EXTENSION_ACTIVATE_FLAG_CONTRACTS,
  EXTENSION_ADOPT_ALL_FLAG_CONTRACTS,
  EXTENSION_ADOPT_FLAG_CONTRACTS,
  EXTENSION_CATALOG_FLAG_CONTRACTS,
  EXTENSION_DEACTIVATE_FLAG_CONTRACTS,
  EXTENSION_DESCRIBE_FLAG_CONTRACTS,
  EXTENSION_DOCTOR_FLAG_CONTRACTS,
  EXTENSION_EXPLORE_FLAG_CONTRACTS,
  EXTENSION_FLAG_CONTRACTS,
  EXTENSION_INIT_FLAG_CONTRACTS,
  EXTENSION_INSTALL_FLAG_CONTRACTS,
  EXTENSION_MANAGE_FLAG_CONTRACTS,
  EXTENSION_RELOAD_FLAG_CONTRACTS,
  EXTENSION_SCOPE_FLAG_CONTRACTS,
  EXTENSION_UNINSTALL_FLAG_CONTRACTS,
  FILES_FLAG_CONTRACTS,
  FOCUS_FLAG_CONTRACTS,
  GC_FLAG_CONTRACTS,
  GET_FLAG_CONTRACTS,
  GLOBAL_FLAG_CONTRACTS,
  GUIDE_FLAG_CONTRACTS,
  HEALTH_FLAG_CONTRACTS,
  HISTORY_COMPACT_FLAG_CONTRACTS,
  HISTORY_FLAG_CONTRACTS,
  HISTORY_REDACT_FLAG_CONTRACTS,
  HISTORY_REPAIR_FLAG_CONTRACTS,
  INIT_FLAG_CONTRACTS,
  INSTALL_FLAG_CONTRACTS,
  LEARNINGS_FLAG_CONTRACTS,
  LIST_COMMANDER_STRING_OPTION_CONTRACTS,
  LIST_FILTER_FLAG_CONTRACTS,
  MEET_FLAG_CONTRACTS,
  NEXT_COMMANDER_STRING_OPTION_CONTRACTS,
  NEXT_FLAG_CONTRACTS,
  NORMALIZE_FLAG_CONTRACTS,
  NOTES_FLAG_CONTRACTS,
  PACKAGE_FLAG_CONTRACTS,
  PACKAGE_INIT_FLAG_CONTRACTS,
  PAUSE_TASK_FLAG_CONTRACTS,
  PLAN_FLAG_CONTRACTS,
  PM_CORE_COMMAND_NAMES,
  PM_EXTENSION_CAPABILITY_CONTRACTS,
  PM_EXTENSION_POLICY_MODE_CONTRACTS,
  PM_EXTENSION_POLICY_SURFACE_CONTRACTS,
  PM_EXTENSION_SANDBOX_PROFILE_CONTRACTS,
  PM_EXTENSION_SERVICE_NAME_CONTRACTS,
  PM_EXTENSION_TRUST_MODE_CONTRACTS,
  PM_PROVIDER_TOOL_PARAMETERS_SCHEMA,
  PM_PROVIDER_TOOL_PARAMETERS_SCHEMA_VERSION,
  PM_TOOL_ACTIONS,
  PM_TOOL_ACTION_PARAMETER_CONTRACTS,
  PM_TOOL_PARAMETERS_SCHEMA,
  PM_TOOL_PARAMETERS_SCHEMA_MAJOR,
  PM_TOOL_PARAMETERS_SCHEMA_VERSION,
  PROFILE_FLAG_CONTRACTS,
  REINDEX_FLAG_CONTRACTS,
  RELEASE_FLAG_CONTRACTS,
  REMIND_FLAG_CONTRACTS,
  RESTORE_FLAG_CONTRACTS,
  SCHEMA_FLAG_CONTRACTS,
  SEARCH_COMMANDER_STRING_OPTION_CONTRACTS,
  SEARCH_FLAG_CONTRACTS,
  START_TASK_FLAG_CONTRACTS,
  STATS_FLAG_CONTRACTS,
  SUBCOMMAND_GLOBAL_FLAG_CONTRACTS,
  TELEMETRY_FLAG_CONTRACTS,
  TEST_ALL_FLAG_CONTRACTS,
  TEST_FLAG_CONTRACTS,
  TEST_RUNS_FLAG_CONTRACTS,
  TOOL_ACTIVITY_OPTION_CONTRACTS,
  TOOL_AGGREGATE_OPTION_CONTRACTS,
  TOOL_CALENDAR_OPTION_CONTRACTS,
  TOOL_CLOSE_MANY_FILTER_OPTION_CONTRACTS,
  TOOL_CONTEXT_OPTION_CONTRACTS,
  TOOL_CREATE_OPTION_CONTRACTS,
  TOOL_DEDUPE_AUDIT_OPTION_CONTRACTS,
  TOOL_DEPS_OPTION_CONTRACTS,
  TOOL_LIST_FILTER_OPTION_CONTRACTS,
  TOOL_NORMALIZE_FILTER_OPTION_CONTRACTS,
  TOOL_SEARCH_FILTER_OPTION_CONTRACTS,
  TOOL_SHARED_CREATE_UPDATE_OPTION_CONTRACTS,
  TOOL_UPDATE_MANY_FILTER_OPTION_CONTRACTS,
  TOOL_UPDATE_OPTION_CONTRACTS,
  UPDATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS,
  UPDATE_COMMANDER_REPEATABLE_OPTION_CONTRACTS,
  UPDATE_COMMANDER_STRING_OPTION_CONTRACTS,
  UPDATE_FLAG_CONTRACTS,
  UPDATE_MANY_FLAG_CONTRACTS,
  UPGRADE_FLAG_CONTRACTS,
  compactFlagAliasContracts,
  isPmExtensionCapabilityContract,
  isPmExtensionPolicyModeContract,
  isPmExtensionPolicySurfaceContract,
  isPmExtensionServiceNameContract,
  isPmToolAction,
  readFirstStringFromCommanderOptions,
  readFirstValueFromCommanderOptions,
  readStringArrayFromCommanderOptions,
  resolveSubcommandFlagContractsForCommand,
  toCompletionFlagString,
  withFlagAliasMetadata,
} from "./cli-contracts.js";
export type {
  CliFlagContract,
  PmActionSchemaContract,
  PmExtensionCapabilityContract,
  PmExtensionPolicyModeContract,
  PmExtensionPolicySurfaceContract,
  PmExtensionSandboxProfileContract,
  PmExtensionServiceNameContract,
  PmExtensionTrustModeContract,
  PmToolAction,
  ToolOptionFlagContract,
} from "./cli-contracts.js";
export * from "./compose.js";
export * from "./define.js";
export {
  BASELINE_ITEM_FORMAT_VERSION,
  BUILTIN_ITEM_TYPE_VALUES,
  CONFIDENCE_TEXT_VALUES,
  CURRENT_ITEM_FORMAT_VERSION,
  DEPENDENCY_KIND_VALUES,
  EXIT_CODE,
  ISSUE_SEVERITY_VALUES,
  ITEM_TYPE_VALUES,
  PM_CLI_EXPECTED_ERROR_NAME,
  PmCliError,
  PmClient,
  RISK_VALUES,
  STATUS_VALUES,
  acquireLock,
  appendHistoryEntry,
  canonicalDocument,
  classifyItemFormatVersion,
  clearWorkspaceContractsCache,
  commitImportedItem,
  createHistoryEntry,
  createPmCliExpectedError,
  effectiveItemFormatVersion,
  emptyImportedDocument,
  ensureTrackerInitialized,
  generateItemId,
  getActiveExtensionRegistrations,
  getContracts,
  getHistoryPath,
  getItemPath,
  getSettingsPath,
  getWorkspaceContracts,
  isPmCliExpectedError,
  isTimestampLiteral,
  listAllFrontMatter,
  loadCreateTemplateOptions,
  locateItem,
  normalizeFrontMatter,
  normalizeItemFormatVersion,
  normalizeItemId,
  normalizeRawItemId,
  normalizeStatusInput,
  nowIso,
  parseTags,
  pathExists,
  readBooleanOption,
  readCsvListOption,
  readFileIfExists,
  readLocatedItem,
  readRequiredString,
  readSettings,
  readStringOption,
  removeFileIfExists,
  renderCalendarMarkdown,
  renderCalendarToon,
  renderGuideMarkdown,
  resolveCalendarOutputFormat,
  resolveGuideOutputFormat,
  resolveItemTypeRegistry,
  resolvePmRoot,
  resolveRuntimeFieldRegistry,
  resolveRuntimeStatusRegistry,
  runAction,
  runActiveOnReadHooks,
  runActiveOnWriteHooks,
  runCalendar,
  runCommentsAudit,
  runCompletion,
  runDedupeAudit,
  runDedupeMerge,
  runGuide,
  runNormalize,
  runReindex,
  runSearch,
  runTemplatesList,
  runTemplatesSave,
  runTemplatesShow,
  runTestRunsList,
  runTestRunsLogs,
  runTestRunsResume,
  runTestRunsStatus,
  runTestRunsStop,
  scanItemFormatVersions,
  selectImportAuthor,
  serializeItemDocument,
  splitFrontMatter,
  toEstimatedMinutesValue,
  toImportBoolean,
  toImportConfidence,
  toImportInteger,
  toImportLinkedDocs,
  toImportLinkedFiles,
  toImportLinkedTests,
  toImportLogEntries,
  toImportNormalizedEnum,
  toImportNumberMap,
  toImportPriority,
  toImportStatus,
  toImportStringList,
  toImportStringMap,
  toImportTags,
  toNonEmptyImportString,
  writeFileAtomic,
  aggregate,
  append,
  claim,
  close,
  closeTask,
  comments,
  config,
  context,
  copy,
  create,
  deleteItem,
  deps,
  docs,
  extension,
  extensionActivate,
  extensionDeactivate,
  extensionList,
  files,
  filesDiscover,
  focus,
  gc,
  get,
  health,
  init,
  learnings,
  list,
  next,
  notes,
  packageActivate,
  packageCatalog,
  packageDeactivate,
  packageDescribe,
  packageDoctor,
  packageInstall,
  packageLifecycle,
  packageList,
  packageManage,
  packageReload,
  packageUninstall,
  pauseTask,
  release,
  restore,
  schema,
  schemaAddField,
  schemaAddStatus,
  schemaAddType,
  schemaApplyPreset,
  schemaInferTypes,
  schemaList,
  schemaListFields,
  schemaRemoveField,
  schemaRemoveStatus,
  schemaRemoveType,
  schemaShow,
  schemaShowField,
  schemaShowStatus,
  search,
  profile,
  profileApply,
  profileLint,
  profileList,
  profileShow,
  startTask,
  stats,
  update,
  upgrade,
  validate,
  type AggregateOptions,
  type AggregateResult,
  type AggregateRow,
  type AppendCommandOptions,
  type AppendResult,
  type BlockerEntry,
  type CalendarOptions,
  type CalendarResult,
  type CommentsAuditEntry,
  type CommentsAuditHistoryRow,
  type CommentsAuditOptions,
  type CommentsAuditResult,
  type CommentsAuditSummary,
  type CommentsAuditTypeSummary,
  type CommitImportedItemParams,
  type CommitImportedItemResult,
  type CommentsCommandOptions,
  type CommentsResult,
  type ConfigCommandOptions,
  type ConfigResult,
  type CompletionResult,
  type CompletionShell,
  type ContractsCommandOptions,
  type ContractsResult,
  type ContextFocusItem,
  type ContextOptions,
  type ContextOutputFormat,
  type ContextResult,
  type CreatePmCliExpectedErrorOptions,
  type CreateTemplateOptions,
  type DedupeAuditCandidate,
  type DedupeAuditCluster,
  type DedupeAuditOptions,
  type DedupeAuditResult,
  type DedupeMergeChildReparent,
  type DedupeMergeCloseAction,
  type DedupeMergeDuplicateOutcome,
  type DedupeMergeOptions,
  type DedupeMergeResult,
  type Dependency,
  type DepsCommandOptions,
  type DepsResult,
  type DocsCommandOptions,
  type DocsResult,
  type ExtensionCommandOptions,
  type ExtensionCommandResult,
  type FilesCommandOptions,
  type FilesDiscoverOptions,
  type FilesDiscoverResult,
  type FilesResult,
  type GcCommandOptions,
  type GcResult,
  type GetContractsOptions,
  type GetOptions,
  type GetResult,
  type GuideDepth,
  type GuideOptions,
  type GuideOutputFormat,
  type GuideResult,
  type HealthResult,
  type ImportLinkedScope,
  type InitCommandOptions,
  type InitResult,
  type ItemFormatVersionScanEntry,
  type ItemFormatVersionScanResult,
  type ItemFormatVersionStatus,
  type ItemMetadata,
  type LearningsCommandOptions,
  type LearningsResult,
  type LinkedDoc,
  type LinkedFile,
  type LinkedTest,
  type ListedItem,
  type ListCompactResult,
  type ListOptions,
  type ListResult,
  type ListSortField,
  type ListSortOrder,
  type ListVerboseResult,
  type LogNote,
  type NextActionableItem,
  type NextBlockerRef,
  type NextOptions,
  type NextOutputFormat,
  type NextRecommendation,
  type NextResult,
  type NormalizeCommandOptions,
  type NormalizeResult,
  type NotesCommandOptions,
  type NotesResult,
  type PackageCommandOptions,
  type PackageCommandResult,
  type PmActionInput,
  type PmActionName,
  type PmActionOptions,
  type PmClientMutationOptions,
  type PmClientOptions,
  type PmClientRunArgs,
  type PmCliExpectedError,
  type ProfileApplyCommandOptions,
  type ProfileApplyResult,
  type ProfileLintResult,
  type ProfileListResult,
  type ProfileResult,
  type ProfileShowResult,
  type ProfileSubcommand,
  type ReindexOptions,
  type ReindexResult,
  type RunHealthOptions,
  type SchemaAddFieldCommandOptions,
  type SchemaAddFieldResult,
  type SchemaAddStatusCommandOptions,
  type SchemaAddStatusResult,
  type SchemaAddTypeCommandOptions,
  type SchemaAddTypeInferCommandOptions,
  type SchemaAddTypeInferResult,
  type SchemaAddTypeResult,
  type SchemaApplyPresetCommandOptions,
  type SchemaApplyPresetResult,
  type SchemaInspectResult,
  type SchemaListFieldsResult,
  type SchemaListResult,
  type SchemaRemoveFieldCommandOptions,
  type SchemaRemoveFieldResult,
  type SchemaRemoveStatusCommandOptions,
  type SchemaRemoveStatusResult,
  type SchemaRemoveTypeCommandOptions,
  type SchemaRemoveTypeResult,
  type SchemaShowFieldResult,
  type SchemaShowResult,
  type SchemaShowStatusResult,
  type SchemaResult,
  type SchemaSubcommand,
  type SearchCompactResult,
  type SearchHit,
  type SearchHitHighlight,
  type SearchMatchMode,
  type SearchOptions,
  type SearchResult,
  type SearchResultItem,
  type SearchVerboseResult,
  type StatsCommandOptions,
  type StatsResult,
  type TemplatesListResult,
  type TemplatesSaveResult,
  type TemplatesShowResult,
  type TestRunsListCommandOptions,
  type TestRunsLogsCommandOptions,
  type TestRunsResumeCommandOptions,
  type TestRunsStopCommandOptions,
  type ToImportLinkedArtifactsOptions,
  type ToImportLinkedTestsOptions,
  type ToImportLogEntriesOptions,
  type UpgradeCommandOptions,
  type UpgradeResult,
  type ValidateCommandOptions,
  type ValidateResult,
  type WorkspaceContracts,
  type WorkspaceContractsOptions,
} from "./runtime.js";
export {
  BUILTIN_PROFILES,
  listProfiles,
  normalizeProfileName,
  PROFILE_NAMES,
  resolveProfile,
  type ProfileConfigEntry,
  type ProfileName,
  type ProfilePackageRecommendation,
  type ProfileTemplateEntry,
  type ProfileTemplateOptions,
  type ProjectProfileDefinition,
  type ProjectProfileRegistrationInput,
} from "../core/profile/profile-presets.js";
export {
  planProfileApplication,
  type ProfileApplicationPlan,
  type ProfileChangeStatus,
  type ProfileComponentChange,
  type ProfileConfigChange,
  type ProfileConfigPlan,
  type ProfileCurrentState,
  type ProfilePackagePlan,
  type ProfileSchemaPlan,
  type ProfileTemplateChange,
  type ProfileTemplatePlan,
  type ProfileWorkflowChange,
  type ProfileWorkflowPlan,
} from "../core/profile/profile-plan.js";
export {
  describeProfileComposition,
  describeProjectProfile,
  type ProjectProfileComposition,
  type ProjectProfileDescription,
  type ProjectProfilePackageSummary,
} from "../core/profile/profile-describe.js";
export {
  lintProjectProfile,
  PROFILE_LINT_CODES,
  PROFILE_LINT_DIMENSIONS,
  type ProfileLintCode,
  type ProfileLintDimension,
  type ProfileLintSeverity,
  type ProjectProfileLintFinding,
  type ProjectProfileLintReport,
} from "../core/profile/profile-lint.js";
export {
  assertExtensionBlueprint,
  assertExtensionCapabilityUsage,
  assertExtensionDeactivated,
  assertExtensionManifestCompatible,
  assertExtensionManifestMatchesBlueprint,
  assertExtensionPreflight,
  assertPackageManifest,
  assertProjectProfile,
  assertRegisteredCommandContract,
  assertRegisteredCommandOverride,
  assertRegisteredExporter,
  assertRegisteredFlags,
  assertRegisteredHook,
  assertRegisteredImporter,
  assertRegisteredItemField,
  assertRegisteredItemType,
  assertRegisteredMigration,
  assertRegisteredParserOverride,
  assertRegisteredPreflightOverride,
  assertRegisteredProfile,
  assertRegisteredRendererOverride,
  assertRegisteredSearchProvider,
  assertRegisteredServiceOverride,
  assertRegisteredVectorStoreAdapter,
  activateExtensionForTest,
  createExtensionTestHarness,
  deactivateExtensionForTest,
  describeExtensionActivation,
  runRegisteredCommandForTest,
  runRegisteredCommandOverrideForTest,
  runRegisteredExporterForTest,
  runRegisteredHookForTest,
  runRegisteredImporterForTest,
  runRegisteredMigrationForTest,
  runRegisteredParserOverrideForTest,
  runRegisteredPreflightOverrideForTest,
  runRegisteredRendererOverrideForTest,
  runRegisteredSearchProviderForTest,
  runRegisteredServiceOverrideForTest,
  runRegisteredVectorStoreAdapterForTest,
  type ActivateExtensionForTestOptions,
  type AssertProjectProfileOptions,
  type DeactivateExtensionForTestOptions,
  type DescribeExtensionActivationOptions,
  type ExtensionActivationSummary,
  type RenderExtensionHarnessMarkdownOptions,
  type RunRegisteredCommandForTestOptions,
  type RunRegisteredExporterForTestOptions,
  type RunRegisteredHookForTestOptions,
  type RunRegisteredImporterForTestOptions,
  type RunRegisteredMigrationForTestOptions,
  type RunRegisteredSearchProviderForTestOptions,
  type RunRegisteredVectorStoreAdapterForTestOptions,
  type SearchProviderOperationContexts,
  type SearchProviderOperationResults,
  type VectorStoreAdapterOperationContexts,
  type VectorStoreAdapterOperationResults,
  type ExtensionCapabilityUsageAssertion,
  type ExtensionCapabilityUsageExpectation,
  type ExtensionDeactivationExpectation,
  type ExtensionManifestBlueprintMatch,
  type ExtensionTestHarness,
  type PackageManifestExpectation,
  type PackageManifestResourceExpectation,
  type RegisteredCommandContractAssertion,
  type RegisteredCommandContractExpectation,
  type RegisteredCommandOverrideExpectation,
  type RegisteredExporterExpectation,
  type RegisteredFlagsExpectation,
  type RegisteredHookExpectation,
  type RegisteredHookKind,
  type RegisteredImporterExpectation,
  type RegisteredItemFieldAssertion,
  type RegisteredItemFieldExpectation,
  type RegisteredItemTypeAssertion,
  type RegisteredItemTypeExpectation,
  type RegisteredMigrationExpectation,
  type RegisteredParserOverrideExpectation,
  type RegisteredPreflightOverrideExpectation,
  type RegisteredProfileAssertion,
  type RegisteredProfileExpectation,
  type RegisteredRendererOverrideExpectation,
  type RegisteredSearchProviderExpectation,
  type RegisteredServiceOverrideExpectation,
  type RegisteredVectorStoreAdapterExpectation,
} from "./testing.js";

/**
 * Canonical extension capability names accepted by pm.
 *
 * Extension manifests should declare one or more of these values in
 * `capabilities`.
 */
export const EXTENSION_CAPABILITIES = KNOWN_EXTENSION_CAPABILITIES;
/**
 * Restricts extension capability values accepted by command, SDK, and storage contracts.
 */
export type ExtensionCapability = (typeof EXTENSION_CAPABILITIES)[number];

/**
 * Canonical extension governance policy modes and registration surfaces.
 */
export const EXTENSION_POLICY_MODES = KNOWN_EXTENSION_POLICY_MODES;
export const EXTENSION_POLICY_SURFACES = KNOWN_EXTENSION_POLICY_SURFACES;
export const EXTENSION_TRUST_MODES = KNOWN_EXTENSION_TRUST_MODES;
export const EXTENSION_SANDBOX_PROFILES = KNOWN_EXTENSION_SANDBOX_PROFILES;
/**
 * Restricts extension policy mode values accepted by command, SDK, and storage contracts.
 */
export type ExtensionPolicyMode = (typeof EXTENSION_POLICY_MODES)[number];
/**
 * Restricts extension policy surface values accepted by command, SDK, and storage contracts.
 */
export type ExtensionPolicySurface = (typeof EXTENSION_POLICY_SURFACES)[number];
/**
 * Restricts extension trust mode values accepted by command, SDK, and storage contracts.
 */
export type ExtensionTrustMode = (typeof EXTENSION_TRUST_MODES)[number];
/**
 * Restricts extension sandbox profile values accepted by command, SDK, and storage contracts.
 */
export type ExtensionSandboxProfile = (typeof EXTENSION_SANDBOX_PROFILES)[number];

/**
 * Versioned capability contract metadata emitted by runtime diagnostics.
 */
export { EXTENSION_CAPABILITY_CONTRACT, EXTENSION_CAPABILITY_CONTRACT_VERSION, EXTENSION_CAPABILITY_LEGACY_ALIASES };

/**
 * Least-privilege capability reconciliation helpers: map declared capabilities
 * against the registration surfaces a package actually exercises at activation.
 */
export {
  EXTENSION_CAPABILITY_REGISTRATION_SURFACES,
  collectUsedExtensionCapabilities,
  reconcileExtensionCapabilityUsage,
  type CollectUsedExtensionCapabilitiesOptions,
  type ExtensionCapabilityUsageReconciliation,
} from "../core/extensions/capability-usage.js";

/**
 * Render an extension/package activation summary
 * ({@link describeExtensionActivation} / {@link describeExtensionBlueprint}) to a
 * deterministic Markdown reference document — the author-facing *render* leg of
 * the describe verb, for drift-free package READMEs.
 */
export {
  renderExtensionSurfaceMarkdown,
  type ExtensionSurfaceMarkdownOptions,
} from "../core/extensions/activation-summary-markdown.js";

export type {
  AfterCommandAffectedItem,
  AfterCommandHook,
  AfterCommandHookContext,
  BeforeCommandHook,
  BeforeCommandHookContext,
  CommandDefinition,
  ExtensionCommandArgumentDefinition,
  CommandHandler,
  CommandHandlerContext,
  CommandHandlerResult,
  CommandOverride,
  CommandOverrideContext,
  ExtensionServiceName,
  Exporter,
  ExtensionActivationResult,
  ExtensionApi,
  ExtensionCommandRegistry,
  ExtensionDeactivationFailure,
  ExtensionDeactivationOptions,
  ExtensionDeactivationResult,
  ExtensionDiagnostic,
  ExtensionDiscoveryResult,
  ExtensionHookRegistry,
  ExtensionSelfIdentity,
  ExtensionLoadResult,
  ExtensionManifest,
  ExtensionManifestEngines,
  ExtensionGovernancePolicy,
  ExtensionPolicyOverride,
  ExtensionProvenanceMetadata,
  ExtensionRuntimePermissionDeclaration,
  ExtensionSearchMode,
  ExtensionParserRegistry,
  ExtensionPreflightRegistry,
  ExtensionRegistrationRegistry,
  ExtensionRendererRegistry,
  ExtensionServiceRegistry,
  FlagValueType,
  FlagDefinition,
  ImportExportContext,
  ImportExportRegistrationOptions,
  Importer,
  OnIndexHook,
  OnIndexHookContext,
  OnReadHook,
  OnReadHookContext,
  OnWriteHook,
  OnWriteHookContext,
  OutputRendererFormat,
  ParserOverride,
  ParserOverrideContext,
  ParserOverrideDelta,
  PreflightOverride,
  PreflightOverrideContext,
  PreflightOverrideDelta,
  PreflightRuntimeDecision,
  RegisteredExtensionExporter,
  RegisteredExtensionFlagDefinitions,
  RegisteredExtensionHook,
  RegisteredExtensionImporter,
  RegisteredExtensionProjectProfile,
  RegisteredExtensionSchemaMigrationDefinition,
  RegisteredExtensionSearchProvider,
  RegisteredExtensionServiceOverride,
  RegisteredExtensionVectorStoreAdapter,
  RendererOverride,
  RendererOverrideContext,
  SchemaFieldDefinition,
  SchemaItemTypeCommandOptionPolicyDefinition,
  SchemaItemTypeOptionDefinition,
  SchemaItemTypeDefinition,
  SchemaMigrationDefinition,
  SchemaMigrationRunContext,
  SchemaMigrationRunner,
  SearchProviderEmbedBatchContext,
  SearchProviderEmbedContext,
  SearchProviderDefinition,
  SearchProviderHit,
  SearchProviderQueryContext,
  SearchProviderQueryResult,
  ServiceOverride,
  ServiceOverrideContext,
  VectorStoreAdapterDefinition,
  VectorStoreDeleteContext,
  VectorStoreQueryContext,
  VectorStoreQueryHit,
  VectorStoreUpsertContext,
  VectorStoreUpsertPoint,
} from "../core/extensions/loader.js";

export type { GlobalOptions } from "../core/shared/command-types.js";
export type { ItemDocument, ItemFrontMatter, ItemStatus, ItemType, PmSettings } from "../types/index.js";
