import type { CommanderOptionAliasContract, CommanderOptionRegistrationContract } from "./commander-types.js";

export const CREATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS: CommanderOptionRegistrationContract[] = [
  {
    target: "title",
    keys: ["title"],
    option: "--title, -t <value>",
    description: "Item title [required] (or pass title as the first positional argument)",
  },
  {
    target: "description",
    keys: ["description"],
    option: "--description, -d <value>",
    description: "Item description (allow empty string)",
  },
  { target: "type", keys: ["type"], option: "--type <value>", description: "Item type (built-ins plus any configured custom types)" },
  { target: "template", keys: ["template"], option: "--template <value>", description: "Apply named create template defaults before explicit flags" },
  {
    target: "createMode",
    keys: ["createMode", "create_mode"],
    option: "--create-mode <value>",
    description: "Create required-option policy mode: strict|progressive",
    aliasOptions: [{ option: "--create_mode <value>", description: "Alias for --create-mode" }],
  },
  {
    target: "schedulePreset",
    keys: ["schedulePreset", "schedule_preset"],
    option: "--schedule-preset <value>",
    description: "Scheduling preset for Reminder|Meeting|Event: lightweight",
    aliasOptions: [{ option: "--schedule_preset <value>", description: "Alias for --schedule-preset" }],
  },
  { target: "status", keys: ["status"], option: "--status, -s <value>", description: "Item status" },
  { target: "priority", keys: ["priority"], option: "--priority, -p <value>", description: "Priority 0..4" },
  { target: "tags", keys: ["tags"], option: "--tags <value>", description: "Comma-separated tags" },
  {
    target: "addTags",
    keys: ["addTags", "add_tags"],
    option: "--add-tags <value>",
    description: "Add tags additively on top of --tags (repeatable; CSV accepted)",
    repeatable: true,
    aliasOptions: [{ option: "--add_tags <value>", description: "Alias for --add-tags" }],
  },
  { target: "body", keys: ["body"], option: "--body, -b <value>", description: "Item markdown body (allow empty string)" },
  { target: "deadline", keys: ["deadline"], option: "--deadline <value>", description: "Deadline (ISO/date string or relative +6h/+1d/+2w/+6m)" },
  {
    target: "estimatedMinutes",
    keys: ["estimate", "estimatedMinutes", "estimated_minutes"],
    option: "--estimate, --estimated-minutes <value>",
    description: "Estimated minutes",
    aliasOptions: [{ option: "--estimated_minutes <value>", description: "Alias for --estimated-minutes" }],
  },
  {
    target: "acceptanceCriteria",
    keys: ["acceptanceCriteria", "acceptance_criteria", "ac"],
    option: "--acceptance-criteria <value>",
    description: "Acceptance criteria (allow empty string)",
    aliasOptions: [
      { option: "--acceptance_criteria <value>", description: "Alias for --acceptance-criteria" },
      { option: "--ac <value>", description: "Alias for --acceptance-criteria" },
    ],
  },
  {
    target: "definitionOfReady",
    keys: ["definitionOfReady", "definition_of_ready"],
    option: "--definition-of-ready <value>",
    description: "Definition of ready (allow empty string)",
    aliasOptions: [{ option: "--definition_of_ready <value>", description: "Alias for --definition-of-ready" }],
  },
  { target: "order", keys: ["order"], option: "--order <value>", description: "Planning order/rank integer" },
  { target: "rank", keys: ["rank"], option: "--rank <value>", description: "Alias for --order" },
  { target: "goal", keys: ["goal"], option: "--goal <value>", description: "Goal identifier" },
  { target: "objective", keys: ["objective"], option: "--objective <value>", description: "Objective identifier" },
  { target: "value", keys: ["value"], option: "--value <value>", description: "Business value summary" },
  { target: "impact", keys: ["impact"], option: "--impact <value>", description: "Business impact summary" },
  { target: "outcome", keys: ["outcome"], option: "--outcome <value>", description: "Expected outcome summary" },
  {
    target: "whyNow",
    keys: ["whyNow", "why_now"],
    option: "--why-now <value>",
    description: "Why-now rationale",
    aliasOptions: [{ option: "--why_now <value>", description: "Alias for --why-now" }],
  },
  { target: "author", keys: ["author"], option: "--author <value>", description: "Mutation author" },
  { target: "message", keys: ["message"], option: "--message <value>", description: "History message (allow empty string)" },
  { target: "assignee", keys: ["assignee"], option: "--assignee <value>", description: "Item assignee" },
  { target: "parent", keys: ["parent"], option: "--parent <value>", description: "Parent item ID" },
  { target: "reviewer", keys: ["reviewer"], option: "--reviewer <value>", description: "Reviewer" },
  { target: "risk", keys: ["risk"], option: "--risk <value>", description: "Risk level: low|med|medium|high|critical (med persists as medium)" },
  {
    target: "confidence",
    keys: ["confidence"],
    option: "--confidence <value>",
    description: "Confidence level: 0..100|low|med|medium|high (med persists as medium)",
  },
  { target: "sprint", keys: ["sprint"], option: "--sprint <value>", description: "Sprint identifier" },
  { target: "release", keys: ["release"], option: "--release <value>", description: "Release identifier" },
  {
    target: "blockedBy",
    keys: ["blockedBy", "blocked_by"],
    option: "--blocked-by <value>",
    description: "Blocked-by item ID or reason",
    aliasOptions: [{ option: "--blocked_by <value>", description: "Alias for --blocked-by" }],
  },
  {
    target: "blockedReason",
    keys: ["blockedReason", "blocked_reason"],
    option: "--blocked-reason <value>",
    description: "Blocked reason",
    aliasOptions: [{ option: "--blocked_reason <value>", description: "Alias for --blocked-reason" }],
  },
  {
    target: "unblockNote",
    keys: ["unblockNote", "unblock_note"],
    option: "--unblock-note <value>",
    description: "Unblock rationale note",
    aliasOptions: [{ option: "--unblock_note <value>", description: "Alias for --unblock-note" }],
  },
  { target: "reporter", keys: ["reporter"], option: "--reporter <value>", description: "Issue reporter" },
  {
    target: "severity",
    keys: ["severity"],
    option: "--severity <value>",
    description: "Issue severity: low|med|medium|high|critical (med persists as medium)",
  },
  { target: "environment", keys: ["environment"], option: "--environment <value>", description: "Issue environment context" },
  {
    target: "reproSteps",
    keys: ["reproSteps", "repro_steps"],
    option: "--repro-steps <value>",
    description: "Issue reproduction steps",
    aliasOptions: [{ option: "--repro_steps <value>", description: "Alias for --repro-steps" }],
  },
  { target: "resolution", keys: ["resolution"], option: "--resolution <value>", description: "Issue resolution summary" },
  {
    target: "expectedResult",
    keys: ["expectedResult", "expected_result", "expected"],
    option: "--expected-result <value>",
    description: "Issue expected behavior",
    aliasOptions: [
      { option: "--expected_result <value>", description: "Alias for --expected-result" },
      { option: "--expected <value>", description: "Short alias for --expected-result" },
    ],
  },
  {
    target: "actualResult",
    keys: ["actualResult", "actual_result", "actual"],
    option: "--actual-result <value>",
    description: "Issue observed behavior",
    aliasOptions: [
      { option: "--actual_result <value>", description: "Alias for --actual-result" },
      { option: "--actual <value>", description: "Short alias for --actual-result" },
    ],
  },
  {
    target: "affectedVersion",
    keys: ["affectedVersion", "affected_version"],
    option: "--affected-version <value>",
    description: "Affected version identifier",
    aliasOptions: [{ option: "--affected_version <value>", description: "Alias for --affected-version" }],
  },
  {
    target: "fixedVersion",
    keys: ["fixedVersion", "fixed_version"],
    option: "--fixed-version <value>",
    description: "Fixed version identifier",
    aliasOptions: [{ option: "--fixed_version <value>", description: "Alias for --fixed-version" }],
  },
  { target: "component", keys: ["component"], option: "--component <value>", description: "Issue component ownership" },
  { target: "regression", keys: ["regression"], option: "--regression <value>", description: "Regression marker: true|false|1|0" },
  {
    target: "customerImpact",
    keys: ["customerImpact", "customer_impact"],
    option: "--customer-impact <value>",
    description: "Customer impact summary",
    aliasOptions: [{ option: "--customer_impact <value>", description: "Alias for --customer-impact" }],
  },
  {
    target: "dep",
    keys: ["dep"],
    option: "--dep <value>",
    description: "Seed dependency entry (key=value CSV, markdown key:value lines, or - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "typeOption",
    keys: ["typeOption", "type_option"],
    option: "--type-option <value>",
    description: "Type option key=value or key=<name>,value=<value> (also accepts key:value and markdown pairs; use - for stdin; repeatable)",
    repeatable: true,
    aliasOptions: [{ option: "--type_option <value>", description: "Alias for --type-option" }],
  },
  {
    target: "unset",
    keys: ["unset"],
    option: "--unset <field>",
    description: "Clear scalar metadata field by name (repeatable)",
    repeatable: true,
  },
  {
    target: "reminder",
    keys: ["reminder"],
    option: "--reminder <value>",
    description: "Seed reminder entry at=<iso|relative>,text=<text> (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "event",
    keys: ["event"],
    option: "--event <value>",
    description: "Seed event entry start=<iso|relative>,end=<iso|relative>,title=<text>,all_day=<true|false>,recur_* fields (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "comment",
    keys: ["comment"],
    option: "--comment <value>",
    description: "Seed comment entry (text=<value> CSV/markdown pairs or - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "note",
    keys: ["note"],
    option: "--note <value>",
    description: "Seed note entry (text=<value> CSV/markdown pairs or - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "learning",
    keys: ["learning"],
    option: "--learning <value>",
    description: "Seed learning entry (text=<value> CSV/markdown pairs or - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "file",
    keys: ["file"],
    option: "--file <value>",
    description: "Seed linked file entry (CSV/markdown pairs or - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "test",
    keys: ["test"],
    option: "--test <value>",
    description: "Seed linked test entry (CSV/markdown pairs or - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "doc",
    keys: ["doc"],
    option: "--doc <value>",
    description: "Seed linked doc entry (CSV/markdown pairs or - for stdin; repeatable)",
    repeatable: true,
  },
];

export const CREATE_COMMANDER_STRING_OPTION_CONTRACTS: CommanderOptionAliasContract[] = CREATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS
  .filter((entry) => entry.repeatable !== true)
  .map((entry) => ({ target: entry.target, keys: entry.keys }));

export const CREATE_COMMANDER_REPEATABLE_OPTION_CONTRACTS: CommanderOptionAliasContract[] =
  CREATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS
    .filter((entry) => entry.repeatable === true)
    .map((entry) => ({ target: entry.target, keys: entry.keys }));

export const UPDATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS: CommanderOptionRegistrationContract[] = [
  { target: "title", keys: ["title"], option: "--title, -t <value>", description: "Set title" },
  { target: "description", keys: ["description"], option: "--description, -d <value>", description: "Set description" },
  { target: "body", keys: ["body"], option: "--body, -b <value>", description: "Set body (allow empty string)" },
  { target: "status", keys: ["status"], option: "--status, -s <value>", description: "Set status (use close command for closed)" },
  {
    target: "closeReason",
    keys: ["closeReason", "close_reason"],
    option: "--close-reason <value>",
    description: "Set close reason",
    aliasOptions: [{ option: "--close_reason <value>", description: "Alias for --close-reason" }],
  },
  { target: "priority", keys: ["priority"], option: "--priority, -p <value>", description: "Set priority" },
  { target: "type", keys: ["type"], option: "--type <value>", description: "Set type" },
  { target: "tags", keys: ["tags"], option: "--tags <value>", description: "Set comma-separated tags (replaces existing). Use --add-tags / --remove-tags to mutate additively." },
  {
    target: "addTags",
    keys: ["addTags", "add_tags"],
    option: "--add-tags <value>",
    description: "Add tags to the existing list without replacing it (repeatable; CSV accepted)",
    repeatable: true,
    aliasOptions: [{ option: "--add_tags <value>", description: "Alias for --add-tags" }],
  },
  {
    target: "removeTags",
    keys: ["removeTags", "remove_tags"],
    option: "--remove-tags <value>",
    description: "Remove tags from the existing list (repeatable; CSV accepted)",
    repeatable: true,
    aliasOptions: [{ option: "--remove_tags <value>", description: "Alias for --remove-tags" }],
  },
  { target: "deadline", keys: ["deadline"], option: "--deadline <value>", description: "Set deadline (ISO/date string or relative)" },
  {
    target: "estimatedMinutes",
    keys: ["estimate", "estimatedMinutes", "estimated_minutes"],
    option: "--estimate, --estimated-minutes <value>",
    description: "Set estimated minutes",
    aliasOptions: [{ option: "--estimated_minutes <value>", description: "Alias for --estimated-minutes" }],
  },
  {
    target: "acceptanceCriteria",
    keys: ["acceptanceCriteria", "acceptance_criteria", "ac"],
    option: "--acceptance-criteria <value>",
    description: "Set acceptance criteria",
    aliasOptions: [
      { option: "--acceptance_criteria <value>", description: "Alias for --acceptance-criteria" },
      { option: "--ac <value>", description: "Alias for --acceptance-criteria" },
    ],
  },
  {
    target: "definitionOfReady",
    keys: ["definitionOfReady", "definition_of_ready"],
    option: "--definition-of-ready <value>",
    description: "Set definition of ready",
    aliasOptions: [{ option: "--definition_of_ready <value>", description: "Alias for --definition-of-ready" }],
  },
  { target: "order", keys: ["order"], option: "--order <value>", description: "Set planning order/rank integer" },
  { target: "rank", keys: ["rank"], option: "--rank <value>", description: "Alias for --order" },
  { target: "goal", keys: ["goal"], option: "--goal <value>", description: "Set goal identifier" },
  { target: "objective", keys: ["objective"], option: "--objective <value>", description: "Set objective identifier" },
  { target: "value", keys: ["value"], option: "--value <value>", description: "Set business value summary" },
  { target: "impact", keys: ["impact"], option: "--impact <value>", description: "Set business impact summary" },
  { target: "outcome", keys: ["outcome"], option: "--outcome <value>", description: "Set expected outcome summary" },
  {
    target: "whyNow",
    keys: ["whyNow", "why_now"],
    option: "--why-now <value>",
    description: "Set why-now rationale",
    aliasOptions: [{ option: "--why_now <value>", description: "Alias for --why-now" }],
  },
  { target: "author", keys: ["author"], option: "--author <value>", description: "Mutation author" },
  { target: "message", keys: ["message"], option: "--message <value>", description: "Mutation message" },
  { target: "assignee", keys: ["assignee"], option: "--assignee <value>", description: "Set assignee" },
  { target: "parent", keys: ["parent"], option: "--parent <value>", description: "Set parent item ID" },
  { target: "reviewer", keys: ["reviewer"], option: "--reviewer <value>", description: "Set reviewer" },
  { target: "risk", keys: ["risk"], option: "--risk <value>", description: "Set risk level: low|med|medium|high|critical (med persists as medium)" },
  {
    target: "confidence",
    keys: ["confidence"],
    option: "--confidence <value>",
    description: "Set confidence level: 0..100|low|med|medium|high (med persists as medium)",
  },
  { target: "sprint", keys: ["sprint"], option: "--sprint <value>", description: "Set sprint identifier" },
  { target: "release", keys: ["release"], option: "--release <value>", description: "Set release identifier" },
  {
    target: "blockedBy",
    keys: ["blockedBy", "blocked_by"],
    option: "--blocked-by <value>",
    description: "Set blocked-by item ID or reason",
    aliasOptions: [{ option: "--blocked_by <value>", description: "Alias for --blocked-by" }],
  },
  {
    target: "blockedReason",
    keys: ["blockedReason", "blocked_reason"],
    option: "--blocked-reason <value>",
    description: "Set blocked reason",
    aliasOptions: [{ option: "--blocked_reason <value>", description: "Alias for --blocked-reason" }],
  },
  {
    target: "unblockNote",
    keys: ["unblockNote", "unblock_note"],
    option: "--unblock-note <value>",
    description: "Set unblock rationale note",
    aliasOptions: [{ option: "--unblock_note <value>", description: "Alias for --unblock-note" }],
  },
  { target: "reporter", keys: ["reporter"], option: "--reporter <value>", description: "Set issue reporter" },
  {
    target: "severity",
    keys: ["severity"],
    option: "--severity <value>",
    description: "Set issue severity: low|med|medium|high|critical (med persists as medium)",
  },
  { target: "environment", keys: ["environment"], option: "--environment <value>", description: "Set issue environment context" },
  {
    target: "reproSteps",
    keys: ["reproSteps", "repro_steps"],
    option: "--repro-steps <value>",
    description: "Set issue reproduction steps",
    aliasOptions: [{ option: "--repro_steps <value>", description: "Alias for --repro-steps" }],
  },
  { target: "resolution", keys: ["resolution"], option: "--resolution <value>", description: "Set issue resolution summary" },
  {
    target: "expectedResult",
    keys: ["expectedResult", "expected_result", "expected"],
    option: "--expected-result <value>",
    description: "Set issue expected behavior",
    aliasOptions: [
      { option: "--expected_result <value>", description: "Alias for --expected-result" },
      { option: "--expected <value>", description: "Short alias for --expected-result" },
    ],
  },
  {
    target: "actualResult",
    keys: ["actualResult", "actual_result", "actual"],
    option: "--actual-result <value>",
    description: "Set issue observed behavior",
    aliasOptions: [
      { option: "--actual_result <value>", description: "Alias for --actual-result" },
      { option: "--actual <value>", description: "Short alias for --actual-result" },
    ],
  },
  {
    target: "affectedVersion",
    keys: ["affectedVersion", "affected_version"],
    option: "--affected-version <value>",
    description: "Set affected version identifier",
    aliasOptions: [{ option: "--affected_version <value>", description: "Alias for --affected-version" }],
  },
  {
    target: "fixedVersion",
    keys: ["fixedVersion", "fixed_version"],
    option: "--fixed-version <value>",
    description: "Set fixed version identifier",
    aliasOptions: [{ option: "--fixed_version <value>", description: "Alias for --fixed-version" }],
  },
  { target: "component", keys: ["component"], option: "--component <value>", description: "Set issue component ownership" },
  { target: "regression", keys: ["regression"], option: "--regression <value>", description: "Set regression marker: true|false|1|0" },
  {
    target: "customerImpact",
    keys: ["customerImpact", "customer_impact"],
    option: "--customer-impact <value>",
    description: "Set customer impact summary",
    aliasOptions: [{ option: "--customer_impact <value>", description: "Alias for --customer-impact" }],
  },
  {
    target: "dep",
    keys: ["dep"],
    option: "--dep <value>",
    description: "Add dependency entries id=<id>,kind=<value>,author=<value>,created_at=<iso|now>,source_kind=<value> (repeatable)",
    repeatable: true,
  },
  {
    target: "depRemove",
    keys: ["depRemove", "dep_remove"],
    option: "--dep-remove <value>",
    description: "Remove dependencies by id or id=<id>,kind=<value>,source_kind=<value> selectors (repeatable)",
    repeatable: true,
    aliasOptions: [{ option: "--dep_remove <value>", description: "Alias for --dep-remove" }],
  },
  {
    target: "comment",
    keys: ["comment"],
    option: "--comment <value>",
    description: "Append comment seed author=<value>,created_at=<iso|now>,text=<value> (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "note",
    keys: ["note"],
    option: "--note <value>",
    description: "Append note seed author=<value>,created_at=<iso|now>,text=<value> (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "learning",
    keys: ["learning"],
    option: "--learning <value>",
    description: "Append learning seed author=<value>,created_at=<iso|now>,text=<value> (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "file",
    keys: ["file"],
    option: "--file <value>",
    description: "Append linked file path=<value>,scope=<project|global>,note=<text> (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "test",
    keys: ["test"],
    option: "--test <value>",
    description: "Append linked test command=<value>,path=<value>,scope=<project|global>,timeout_seconds=<n>,pm_context_mode=<schema|tracker|auto> (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "doc",
    keys: ["doc"],
    option: "--doc <value>",
    description: "Append linked doc path=<value>,scope=<project|global>,note=<text> (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "reminder",
    keys: ["reminder"],
    option: "--reminder <value>",
    description: "Set reminders at=<iso|relative>,text=<text> (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "event",
    keys: ["event"],
    option: "--event <value>",
    description: "Set events start=<iso|relative>,end=<iso|relative>,title=<text>,all_day=<true|false>,recur_* fields (also accepts markdown pairs and - for stdin; repeatable)",
    repeatable: true,
  },
  {
    target: "typeOption",
    keys: ["typeOption", "type_option"],
    option: "--type-option <value>",
    description: "Set type options key=value or key=<name>,value=<value> (also accepts key:value and markdown pairs; use - for stdin; repeatable)",
    repeatable: true,
    aliasOptions: [{ option: "--type_option <value>", description: "Alias for --type-option" }],
  },
  {
    target: "unset",
    keys: ["unset"],
    option: "--unset <field>",
    description: "Clear scalar metadata field by name (repeatable)",
    repeatable: true,
  },
];

export const UPDATE_COMMANDER_STRING_OPTION_CONTRACTS: CommanderOptionAliasContract[] = UPDATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS
  .filter((entry) => entry.repeatable !== true)
  .map((entry) => ({ target: entry.target, keys: entry.keys }));

export const UPDATE_COMMANDER_REPEATABLE_OPTION_CONTRACTS: CommanderOptionAliasContract[] =
  UPDATE_COMMANDER_OPTION_REGISTRATION_CONTRACTS
    .filter((entry) => entry.repeatable === true)
    .map((entry) => ({ target: entry.target, keys: entry.keys }));
