import type { ToolOptionFlagContract } from "../cli-contracts.js";

export const TOOL_LIST_FILTER_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "status", flag: "--status" },
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "deadlineBefore", flag: "--deadline-before" },
  { param: "deadlineAfter", flag: "--deadline-after" },
  { param: "assignee", flag: "--assignee" },
  { param: "assigneeFilter", flag: "--assignee-filter" },
  { param: "parent", flag: "--parent" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
  { param: "limit", flag: "--limit" },
  { param: "offset", flag: "--offset" },
  { param: "fields", flag: "--fields" },
  { param: "sort", flag: "--sort" },
  { param: "order", flag: "--order" },
];

export const TOOL_AGGREGATE_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "groupBy", flag: "--group-by" },
  { param: "status", flag: "--status" },
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "deadlineBefore", flag: "--deadline-before" },
  { param: "deadlineAfter", flag: "--deadline-after" },
  { param: "assignee", flag: "--assignee" },
  { param: "assigneeFilter", flag: "--assignee-filter" },
  { param: "parent", flag: "--parent" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
];

export const TOOL_DEDUPE_AUDIT_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "mode", flag: "--mode" },
  { param: "limit", flag: "--limit" },
  { param: "threshold", flag: "--threshold" },
  { param: "status", flag: "--status" },
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "deadlineBefore", flag: "--deadline-before" },
  { param: "deadlineAfter", flag: "--deadline-after" },
  { param: "assignee", flag: "--assignee" },
  { param: "assigneeFilter", flag: "--assignee-filter" },
  { param: "parent", flag: "--parent" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
];

export const TOOL_SEARCH_FILTER_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "deadlineBefore", flag: "--deadline-before" },
  { param: "deadlineAfter", flag: "--deadline-after" },
  { param: "fields", flag: "--fields" },
  { param: "limit", flag: "--limit" },
];

export const TOOL_SHARED_CREATE_UPDATE_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "parent", flag: "--parent" },
  { param: "reviewer", flag: "--reviewer" },
  { param: "risk", flag: "--risk" },
  { param: "confidence", flag: "--confidence" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
  { param: "blockedBy", flag: "--blocked-by" },
  { param: "blockedReason", flag: "--blocked-reason" },
  { param: "unblockNote", flag: "--unblock-note" },
  { param: "reporter", flag: "--reporter" },
  { param: "severity", flag: "--severity" },
  { param: "environment", flag: "--environment" },
  { param: "reproSteps", flag: "--repro-steps" },
  { param: "resolution", flag: "--resolution" },
  { param: "expectedResult", flag: "--expected-result" },
  { param: "actualResult", flag: "--actual-result" },
  { param: "affectedVersion", flag: "--affected-version" },
  { param: "fixedVersion", flag: "--fixed-version" },
  { param: "component", flag: "--component" },
  { param: "regression", flag: "--regression", booleanish: true },
  { param: "customerImpact", flag: "--customer-impact" },
  { param: "definitionOfReady", flag: "--definition-of-ready", allowEmpty: true },
  { param: "order", flag: "--order" },
  { param: "goal", flag: "--goal" },
  { param: "objective", flag: "--objective" },
  { param: "value", flag: "--value" },
  { param: "impact", flag: "--impact" },
  { param: "outcome", flag: "--outcome" },
  { param: "whyNow", flag: "--why-now" },
];

export const TOOL_CREATE_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "title", flag: "--title" },
  { param: "description", flag: "--description", allowEmpty: true },
  { param: "type", flag: "--type" },
  { param: "template", flag: "--template" },
  { param: "createMode", flag: "--create-mode" },
  { param: "schedulePreset", flag: "--schedule-preset" },
  { param: "status", flag: "--status" },
  { param: "priority", flag: "--priority" },
  { param: "tags", flag: "--tags", allowEmpty: true },
  { param: "addTags", flag: "--add-tags", repeatable: true },
  { param: "body", flag: "--body", allowEmpty: true },
  { param: "deadline", flag: "--deadline" },
  { param: "estimate", flag: "--estimate" },
  { param: "acceptanceCriteria", flag: "--acceptance-criteria", allowEmpty: true },
  { param: "author", flag: "--author" },
  { param: "message", flag: "--message", allowEmpty: true },
  { param: "assignee", flag: "--assignee" },
  { param: "reminder", flag: "--reminder", repeatable: true },
  { param: "event", flag: "--event", repeatable: true },
  { param: "typeOption", flag: "--type-option", repeatable: true },
  { param: "field", flag: "--field", repeatable: true },
  { param: "dep", flag: "--dep", repeatable: true },
  { param: "comment", flag: "--comment", repeatable: true },
  { param: "note", flag: "--note", repeatable: true },
  { param: "learning", flag: "--learning", repeatable: true },
  { param: "linkedFile", flag: "--file", repeatable: true },
  { param: "linkedTest", flag: "--test", repeatable: true },
  { param: "doc", flag: "--doc", repeatable: true },
  { param: "unset", flag: "--unset", repeatable: true },
  { param: "clearDeps", flag: "--clear-deps" },
  { param: "clearComments", flag: "--clear-comments" },
  { param: "clearNotes", flag: "--clear-notes" },
  { param: "clearLearnings", flag: "--clear-learnings" },
  { param: "clearFiles", flag: "--clear-files" },
  { param: "clearTests", flag: "--clear-tests" },
  { param: "clearDocs", flag: "--clear-docs" },
  { param: "clearReminders", flag: "--clear-reminders" },
  { param: "clearEvents", flag: "--clear-events" },
  { param: "clearTypeOptions", flag: "--clear-type-options" },
];

export const TOOL_UPDATE_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "title", flag: "--title" },
  { param: "description", flag: "--description", allowEmpty: true },
  { param: "body", flag: "--body", allowEmpty: true },
  { param: "status", flag: "--status" },
  { param: "closeReason", flag: "--close-reason" },
  { param: "priority", flag: "--priority" },
  { param: "type", flag: "--type" },
  { param: "tags", flag: "--tags", allowEmpty: true },
  { param: "addTags", flag: "--add-tags", repeatable: true },
  { param: "removeTags", flag: "--remove-tags", repeatable: true },
  { param: "deadline", flag: "--deadline" },
  { param: "estimate", flag: "--estimate" },
  { param: "acceptanceCriteria", flag: "--acceptance-criteria", allowEmpty: true },
  { param: "author", flag: "--author" },
  { param: "message", flag: "--message", allowEmpty: true },
  { param: "assignee", flag: "--assignee" },
  { param: "dep", flag: "--dep", repeatable: true },
  { param: "depRemove", flag: "--dep-remove", repeatable: true },
  { param: "replaceDeps", flag: "--replace-deps" },
  { param: "replaceTests", flag: "--replace-tests" },
  { param: "comment", flag: "--comment", repeatable: true },
  { param: "note", flag: "--note", repeatable: true },
  { param: "learning", flag: "--learning", repeatable: true },
  { param: "linkedFile", flag: "--file", repeatable: true },
  { param: "linkedTest", flag: "--test", repeatable: true },
  { param: "doc", flag: "--doc", repeatable: true },
  { param: "reminder", flag: "--reminder", repeatable: true },
  { param: "event", flag: "--event", repeatable: true },
  { param: "typeOption", flag: "--type-option", repeatable: true },
  { param: "field", flag: "--field", repeatable: true },
  { param: "unset", flag: "--unset", repeatable: true },
  { param: "clearDeps", flag: "--clear-deps" },
  { param: "clearComments", flag: "--clear-comments" },
  { param: "clearNotes", flag: "--clear-notes" },
  { param: "clearLearnings", flag: "--clear-learnings" },
  { param: "clearFiles", flag: "--clear-files" },
  { param: "clearTests", flag: "--clear-tests" },
  { param: "clearDocs", flag: "--clear-docs" },
  { param: "clearReminders", flag: "--clear-reminders" },
  { param: "clearEvents", flag: "--clear-events" },
  { param: "clearTypeOptions", flag: "--clear-type-options" },
  { param: "allowAuditUpdate", flag: "--allow-audit-update" },
  { param: "allowAuditDepUpdate", flag: "--allow-audit-dep-update" },
];

export const TOOL_UPDATE_MANY_FILTER_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "filterStatus", flag: "--filter-status" },
  { param: "filterType", flag: "--filter-type" },
  { param: "filterTag", flag: "--filter-tag" },
  { param: "filterPriority", flag: "--filter-priority" },
  { param: "filterDeadlineBefore", flag: "--filter-deadline-before" },
  { param: "filterDeadlineAfter", flag: "--filter-deadline-after" },
  { param: "filterAssignee", flag: "--filter-assignee" },
  { param: "filterAssigneeFilter", flag: "--filter-assignee-filter" },
  { param: "filterParent", flag: "--filter-parent" },
  { param: "filterSprint", flag: "--filter-sprint" },
  { param: "filterRelease", flag: "--filter-release" },
  { param: "limit", flag: "--limit" },
  { param: "offset", flag: "--offset" },
];

export const TOOL_NORMALIZE_FILTER_OPTION_CONTRACTS: ToolOptionFlagContract[] = [...TOOL_UPDATE_MANY_FILTER_OPTION_CONTRACTS];

export const TOOL_CALENDAR_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "view", flag: "--view" },
  { param: "date", flag: "--date" },
  { param: "from", flag: "--from" },
  { param: "to", flag: "--to" },
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "status", flag: "--status" },
  { param: "assignee", flag: "--assignee" },
  { param: "assigneeFilter", flag: "--assignee-filter" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
  { param: "include", flag: "--include" },
  { param: "recurrenceLookaheadDays", flag: "--recurrence-lookahead-days" },
  { param: "recurrenceLookbackDays", flag: "--recurrence-lookback-days" },
  { param: "occurrenceLimit", flag: "--occurrence-limit" },
  { param: "limit", flag: "--limit" },
  { param: "format", flag: "--format" },
];

export const TOOL_ACTIVITY_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "id", flag: "--id" },
  { param: "op", flag: "--op" },
  { param: "author", flag: "--author" },
  { param: "from", flag: "--from" },
  { param: "to", flag: "--to" },
  { param: "limit", flag: "--limit" },
  { param: "compact", flag: "--compact" },
  { param: "full", flag: "--full" },
];

export const TOOL_CONTEXT_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "date", flag: "--date" },
  { param: "from", flag: "--from" },
  { param: "to", flag: "--to" },
  { param: "type", flag: "--type" },
  { param: "tag", flag: "--tag" },
  { param: "priority", flag: "--priority" },
  { param: "assignee", flag: "--assignee" },
  { param: "assigneeFilter", flag: "--assignee-filter" },
  { param: "sprint", flag: "--sprint" },
  { param: "release", flag: "--release" },
  { param: "limit", flag: "--limit" },
  { param: "format", flag: "--format" },
  { param: "depth", flag: "--depth" },
  { param: "section", flag: "--section", repeatable: true },
  { param: "activityLimit", flag: "--activity-limit" },
  { param: "staleThreshold", flag: "--stale-threshold" },
];

export const TOOL_DEPS_OPTION_CONTRACTS: ToolOptionFlagContract[] = [
  { param: "format", flag: "--format" },
  { param: "maxDepth", flag: "--max-depth" },
  { param: "collapse", flag: "--collapse" },
  { param: "summary", flag: "--summary" },
];
